$ENFPWDHIST = C:\facts\enfpwdhist_111_actual.ps1
"enfpwdhist_111_actual : $ENFPWDHIST"
$MAXPWDAGE = C:\facts\maxpwdage_112_actual.ps1
"maxpwdage_112_actual : $MAXPWDAGE"
$MINPWDAGE = C:\facts\minpwdage_113_actual.ps1
"minpwdage_113_actual : $MINPWDAGE"
$MINPWDLEN = C:\facts\minpwdlen_114_actual.ps1
"minpwdlen_114_actual : $MINPWDLEN"
$PWDCOMPLEX = C:\facts\pwdcomplex_115_actual.ps1
"pwdcomplex_115_actual : $PWDCOMPLEX"
$REVERSEPATH = C:\facts\reversepath_116_actual.ps1
"reversepath_116_actual : $REVERSEPATH"
$ACCLOCKDUR = C:\facts\acclockdur_121_actual.ps1
"acclockdur_121_actual : $ACCLOCKDUR"
$ACCLOCKTHRES = C:\facts\acclockthres_122_actual.ps1
"acclockthres_122_actual : $ACCLOCKTHRES"
$RESETACCLOCK = C:\facts\resetacclock_123_actual.ps1
"resetacclock_123_actual : $RESETACCLOCK"
$ACCESSCREDMGR = C:\facts\accesscredmgr_221_actual.ps1
"accesscredmgr_221_actual : $ACCESSCREDMGR"
$ACCESSCOMPDC = C:\facts\accesscompdc_222_actual.ps1
"accesscompdc_222_actual : $ACCESSCOMPDC"
$ACTASOS = C:\facts\actasos_224_actual.ps1
"actasos_224_actual : $ACTASOS"
$ADDWSDOMAIN = C:\facts\addwsdomain_225_actual.ps1
"addwsdomain_225_actual : $ADDWSDOMAIN"
$MEMQUOTAPROCESS = C:\facts\memquotaprocess_226_actual.ps1
"memquotaprocess_226_actual : $MEMQUOTAPROCESS"
$ALLOWLOGLOCAL = C:\facts\allowloglocal_227_actual.ps1
"allowloglocal_227_actual : $ALLOWLOGLOCAL"
$ALLOWLOGREMDESKDC = C:\facts\allowlogremdeskdc_228_actual.ps1
"allowlogremdeskdc_228_actual : $ALLOWLOGREMDESKDC"
$BACKUPFILEDIRS = C:\facts\backupfiledirs_2210_actual.ps1
"backupfiledirs_2210_actual : $BACKUPFILEDIRS"
$CHGSYSTIME = C:\facts\chgsystime_2211_actual.ps1
"chgsystime_2211_actual : $CHGSYSTIME"
$CHGTIMEZONE = C:\facts\chgtimezone_2212_actual.ps1
"chgtimezone_2212_actual : $CHGTIMEZONE"
$PAGEFILE = C:\facts\pagefile_2213_actual.ps1
"pagefile_2213_actual : $PAGEFILE"
$TOKENOBJ = C:\facts\tokenobj_2214_actual.ps1
"tokenobj_2214_actual : $TOKENOBJ"
$GLOBALOBJ = C:\facts\globalobj_2215_actual.ps1
"globalobj_2215_actual : $GLOBALOBJ"
$PERMSHAREDOBJ = C:\facts\permsharedobj_2216_actual.ps1
"permsharedobj_2216_actual : $PERMSHAREDOBJ"
$SYMBOLICLINKSDC = C:\facts\symboliclinksdc_2217_actual.ps1
"symboliclinksdc_2217_actual : $SYMBOLICLINKSDC"
$DEBUGPROG = C:\facts\debugprog_2219_actual.ps1
"debugprog_2219_actual : $DEBUGPROG"
$DENYACCESSDC = C:\facts\denyaccessdc_2220_actual.ps1
"denyaccessdc_2220_actual : $DENYACCESSDC"
$DENYLOGBATCHJOB = C:\facts\denylogbatchjob_2222_actual.ps1
"denylogbatchjob_2222_actual : $DENYLOGBATCHJOB"
$DENYLOGSERVICE = C:\facts\denylogservice_2223_actual.ps1
"denylogservice_2223_actual : $DENYLOGSERVICE"
$DENYLOGLOCALLY = C:\facts\denyloglocally_2224_actual.ps1
"denyloglocally_2224_actual : $DENYLOGLOCALLY"
$DENYLOGREMDESKDC = C:\facts\denylogremdeskdc_2225_actual.ps1
"denylogremdeskdc_2225_actual : $DENYLOGREMDESKDC"
$ENBCOMPUSRACCDC = C:\facts\enbcompusraccdc_2227_actual.ps1
"enbcompusraccdc_2227_actual : $ENBCOMPUSRACCDC"
$FORCESHUTDOWN = C:\facts\forceshutdown_2229_actual.ps1
"forceshutdown_2229_actual : $FORCESHUTDOWN"
$SECURITYAUDITS = C:\facts\securityaudits_2230_actual.ps1
"securityaudits_2230_actual : $SECURITYAUDITS"
$CLIENTAUTHENDC = C:\facts\clientauthendc_2231_actual.ps1
"clientauthendc_2231_actual : $CLIENTAUTHENDC"
$INCSCHEDPRIOR = C:\facts\incschedprior_2233_actual.ps1
"incschedprior_2233_actual : $INCSCHEDPRIOR"
$LOADUNLOADDEVDRIVER = C:\facts\loadunloaddevdriver_2234_actual.ps1
"loadunloaddevdriver_2234_actual : $LOADUNLOADDEVDRIVER"
$LOCKPAGEMEM = C:\facts\lockpagemem_2235_actual.ps1
"lockpagemem_2235_actual : $LOCKPAGEMEM"
$LOGBATCHJOB = C:\facts\logbatchjob_2236_actual.ps1
"logbatchjob_2236_actual : $LOGBATCHJOB"
$AUDSECURLOGDC = C:\facts\audsecurlogdc_2237_actual.ps1
"audsecurlogdc_2237_actual : $AUDSECURLOGDC"
$MODFIRMENV = C:\facts\modobjlabel_2239_actual.ps1
"modobjlabel_2239_actual : $MODFIRMENV"
$MODFIRMENV = C:\facts\modfirmenv_2240_actual.ps1
"modfirmenv_2240_actual : $MODFIRMENV"
$VOLMAINTASKS = C:\facts\volmaintasks_2241_actual.ps1
"volmaintasks_2241_actual : $VOLMAINTASKS"
$PROFSINGLEPO = C:\facts\profsinglepro_2242_actual.ps1
"profsinglepro_2242_actual : $PROFSINGLEPO"
$PROFSYSPERF = C:\facts\profsysperf_2243_actual.ps1
"profsysperf_2243_actual : $PROFSYSPERF"
$REPLPROTAKEN = C:\facts\replprotoken_2244_actual.ps1
"replprotoken_2244_actual : $REPLPROTAKEN"
$RESTOREFILEDIRS = C:\facts\restorefiledirs_2245_actual.ps1
"restorefiledirs_2245_actual : $RESTOREFILEDIRS"
$SHUTDOWNSYS = C:\facts\shutdownsys_2246_actual.ps1
"shutdownsys_2246_actual : $SHUTDOWNSYS"
$SYNCDIRSERDATA = C:\facts\syncdirserdata_2247_actual.ps1
"syncdirserdata_2247_actual : $SYNCDIRSERDATA"
$OWNERSHIPFILE = C:\facts\ownershipfile_2248_actual.ps1
"ownershipfile_2248_actual : $OWNERSHIPFILE"
$BLOCKMSACC = C:\facts\blockmsacc_2312_actual.ps1
"blockmsacc_2312_actual : $BLOCKMSACC"
$LIMITLOCACCUSE = C:\facts\limitlocaccuse_2314_actual.ps1
"limitlocaccuse_2314_actual : $LIMITLOCACCUSE"
$RENAMEADACC = C:\facts\renameadmacc_2315_actual.ps1
"renameadmacc_2315_actual : $RENAMEADACC"
$RENAMEGUESTACC = C:\facts\renameguestacc_2316_actual.ps1
"renameguestacc_2316_actual : $RENAMEGUESTACC"
$FORCEAUDPOLICY = C:\facts\forceaudpolicy_2321_actual.ps1
"forceaudpolicy_2321_actual : $FORCEAUDPOLICY"
$SYSSHUTDOWNSECURAUD = C:\facts\sysshutdownsecuraud_2322_actual.ps1
"sysshutdownsecuraud_2322_actual : $SYSSHUTDOWNSECURAUD"
$ALLOWREMOVMEDIA = C:\facts\allowremovmedia_2341_actual.ps1
"allowremovmedia_2341_actual : $ALLOWREMOVMEDIA"
$PREVENTUSR = C:\facts\preventusr_2342_actual.ps1
"preventusr_2342_actual : $PREVENTUSR"
$ALLOWSERVSCHEDTASK = C:\facts\allowservschedtask_2351_actual.ps1
"allowservschedtask_2351_actual : $ALLOWSERVSCHEDTASK"
$LDAPSERVSIGN = C:\facts\ldapservsign_2352_actual.ps1
"ldapservsign_2352_actual : $LDAPSERVSIGN"
$REFUSEMACHACCPWD = C:\facts\refusemachaccpwd_2353_actual.ps1
"refusemachaccpwd_2353_actual : $REFUSEMACHACCPWD"
$DIGIENCRYPTSIGN = C:\facts\digiencryptsign_2361_actual.ps1
"digiencryptsign_2361_actual : $DIGIENCRYPTSIGN"
$DIGIENCRYPSECDATA = C:\facts\digiencrypsecdata_2362_actual.ps1
"digiencrypsecdata_2362_actual : $DIGIENCRYPSECDATA"
$DIGISIGNSECDATA = C:\facts\digisignsecdata_2363_actual.ps1
"digisignsecdata_2363_actual : $DIGISIGNSECDATA"
$DISMACHACCPWDCHG = C:\facts\dismachaccpwdchg_2364_actual.ps1
"dismachaccpwdchg_2364_actual : $DISMACHACCPWDCHG"
$MAXMACHACCPWDAGE = C:\facts\maxmachaccpwdage_2365_actual.ps1
"maxmachaccpwdage_2365_actual : $MAXMACHACCPWDAGE"
$REQSESSIONKEY = C:\facts\reqsessionkey_2366_actual.ps1
"reqsessionkey_2366_actual : $REQSESSIONKEY"
$DONTDISPLASTUSRNAME = C:\facts\dontdisplastusrname_2371_actual.ps1
"dontdisplastusrname_2371_actual : $DONTDISPLASTUSRNAME"
$DONTREQCTRLALTDEL = C:\facts\dontreqctrlaltdel_2372_actual.ps1
"dontreqctrlaltdel_2372_actual : $DONTREQCTRLALTDEL"
$MACHINACTLIMIT = C:\facts\machinactlimit_2373_actual.ps1
"machinactlimit_2373_actual : $MACHINACTLIMIT"
$MSGTEXTUSR = C:\facts\msgtextusr_2374_actual.ps1
"msgtextusr_2374_actual : $MSGTEXTUSR"
$MSGTITLEUSR = C:\facts\msgtitleusr_2375_actual.ps1
"msgtitleusr_2375_actual : $MSGTITLEUSR"
$PROMPTUSRCHGPWD = C:\facts\promptusrchgpwd_2377_actual.ps1
"promptusrchgpwd_2377_actual : $PROMPTUSRCHGPWD"
$SMARTCARDREMOVAL = C:\facts\smartcardremoval_2379_actual.ps1
"smartcardremoval_2379_actual : $SMARTCARDREMOVAL"
$DIGISIGNCLIENT = C:\facts\digisignclient_2381_actual.ps1
"digisignclient_2381_actual : $DIGISIGNCLIENT"
$DIGISIGNSERVAGREE = C:\facts\digisignservagree_2382_actual.ps1
"digisignservagree_2382_actual : $DIGISIGNSERVAGREE"
$SENDUNENCRYPPWD = C:\facts\sendunencryppwd_2383_actual.ps1
"sendunencryppwd_2383_actual : $SENDUNENCRYPPWD"
$SETIDLETIME = C:\facts\setidletime_2391_actual.ps1
"setidletime_2391_actual : $SETIDLETIME"
$DIGISIGNSERV = C:\facts\digisignserv_2392_actual.ps1
"digisignserv_2392_actual : $DIGISIGNSERV"
$DIGISIGNCLIAGREE = C:\facts\digisigncliagree_2393_actual.ps1
"digisigncliagree_2393_actual : $DIGISIGNCLIAGREE"
$DISCONCLILOGONHREXP = C:\facts\disconclilogonhrexp_2394_actual.ps1
"disconclilogonhrexp_2394_actual : $DISCONCLILOGONHREXP"
$ALLOWANONYSID = C:\facts\allowanonysid_23101_actual.ps1
"allowanonysid_23101_actual : $ALLOWANONYSID"
$DONTALLOWSTORAGEPWDCRED = C:\facts\dontallowstoragepwdcred_23104_actual.ps1
"dontallowstoragepwdcred_23104_actual : $DONTALLOWSTORAGEPWDCRED"
$ANONYUSRPERM = C:\facts\anonyusrperm_23105_actual.ps1
"anonyusrperm_23105_actual : $ANONYUSRPERM"
$NAMEDPIPESDC = C:\facts\namedpipesdc_23106_actual.ps1
"namedpipesdc_23106_actual : $NAMEDPIPESDC"
$REMOTEACCESREGPATH = C:\facts\remoteaccesregpath_23108_actual.ps1
"remoteaccesregpath_23108_actual : $REMOTEACCESREGPATH"
$REMOTEACCESREGSUBPATH = C:\facts\remoteaccesregsubpath_23109_actual.ps1
"remoteaccesregsubpath_23109_actual : $REMOTEACCESREGSUBPATH"
$RESTRICTANONYACCES = C:\facts\restrictanonyacces_231010_actual.ps1
"restrictanonyacces_231010_actual : $RESTRICTANONYACCES"
$SHARESACCESS = C:\facts\sharesaccess_231011_actual.ps1
"sharesaccess_231011_actual : $SHARESACCESS"
$SHARESECURLOCALACC = C:\facts\sharesecurlocalacc_231012_actual.ps1
"sharesecurlocalacc_231012_actual : $SHARESECURLOCALACC"
$ALLOWLOCALSYS = C:\facts\allowlocalsys_23111_actual.ps1
"allowlocalsys_23111_actual : $ALLOWLOCALSYS"
$ALLOWLOCALSYSNULL = C:\facts\allowlocalsysnull_23112_actual.ps1
"allowlocalsysnull_23112_actual : $ALLOWLOCALSYSNULL"
$ALLOWPKU2UAUTHEN = C:\facts\allowpku2uauthen_23113_actual.ps1
"allowpku2uauthen_23113_actual : $ALLOWPKU2UAUTHEN"
$KERBEROSENCRYP = C:\facts\kerberosencryp_23114_actual.ps1
"kerberosencryp_23114_actual : $KERBEROSENCRYP"
$DONTSTORELANHASHVAL = C:\facts\dontstorelanhashval_23115_actual.ps1
"dontstorelanhashval_23115_actual : $DONTSTORELANHASHVAL"
$FORCELOGOFF = C:\facts\forcelogoff_23116_actual.ps1
"forcelogoff_23116_actual : $FORCELOGOFF"
$LANMGRAUTHEN = C:\facts\lanmgrauthen_23117_actual.ps1
"lanmgrauthen_23117_actual : $LANMGRAUTHEN"
$LDAPCLISIGN = C:\facts\ldapclisign_23118_actual.ps1
"ldapclisign_23118_actual : $LDAPCLISIGN"
$MINSESSIONSECURCLI = C:\facts\minsessionsecurcli_23119_actual.ps1
"minsessionsecurcli_23119_actual : $MINSESSIONSECURCLI"
$MINSESSIONSECURSERV = C:\facts\minsessionsecurserv_231110_actual.ps1
"minsessionsecurserv_231110_actual : $MINSESSIONSECURSERV"
$ALLOWSYSSHUTDOWN = C:\facts\allowsysshutdown_23131_actual.ps1
"allowsysshutdown_23131_actual : $ALLOWSYSSHUTDOWN"
$CASEINSENSNONWINS = C:\facts\caseinsensnonwins_23151_actual.ps1
"caseinsensnonwins_23151_actual : $CASEINSENSNONWINS"
$STRENGTHDEFAULTPERM = C:\facts\strengthdefaultperm_23152_actual.ps1
"strengthdefaultperm_23152_actual : $STRENGTHDEFAULTPERM"
$SETUSRACCCTRL = C:\facts\setusraccctrl_23171_actual.ps1
"setusraccctrl_23171_actual : $SETUSRACCCTRL"
$ELEVATIONPROMPTADMIN = C:\facts\elevationpromptadmin_23172_actual.ps1
"elevationpromptadmin_23172_actual : $ELEVATIONPROMPTADMIN"
$ELEVATIONPROMPTUSR = C:\facts\elevationpromptusr_23173_actual.ps1
"elevationpromptusr_23173_actual : $ELEVATIONPROMPTUSR"
$DETECTAPPINSTAL = C:\facts\detectappinstal_23174_actual.ps1
"detectappinstal_23174_actual : $DETECTAPPINSTAL"
$ELEVATEUIACCESS = C:\facts\elevateuiaccess_23175_actual.ps1
"elevateuiaccess_23175_actual : $ELEVATEUIACCESS"
$RUNALLADMINISTRATOR = C:\facts\runalladministrator_23176_actual.ps1
"runalladministrator_23176_actual : $RUNALLADMINISTRATOR"
$SWITCHSECUREDESKTOP = C:\facts\switchsecuredesktop_23177_actual.ps1
"switchsecuredesktop_23177_actual : $SWITCHSECUREDESKTOP"
$VIRTUALIZEFILEREGISTRY = C:\facts\virtualizefileregistry_23178_actual.ps1
"virtualizefileregistry_23178_actual : $VIRTUALIZEFILEREGISTRY"
$DOMAINFIREWALLSTATE = C:\facts\domainfirewallstate_911_actual.ps1
"domainfirewallstate_911_actual : $DOMAINFIREWALLSTATE"
$INBOUNDCONN = C:\facts\inboundconn_912_actual.ps1
"inboundconn_912_actual : $INBOUNDCONN"
$OUTBOUNDCONN = C:\facts\outboundconn_913_actual.ps1
"outboundconn_913_actual : $OUTBOUNDCONN"
$DISABLENOTIFICDISPLAY = C:\facts\disablenotificdisplay_914_actual.ps1
"disablenotificdisplay_914_actual : $DISABLENOTIFICDISPLAY"
$LOGGINGNAME = C:\facts\loggingname_915_actual.ps1
"loggingname_915_actual : $LOGGINGNAME"
$LOGGINGSIZELIMIT = C:\facts\loggingsizelimit_916_actual.ps1
"loggingsizelimit_916_actual : $LOGGINGSIZELIMIT"
$LOGGINGLOGDROPPACK = C:\facts\logginglogdroppack_917_actual.ps1
"logginglogdroppack_917_actual : $LOGGINGLOGDROPPACK"
$LOGGINGLOGSUCCESS = C:\facts\logginglogsuccess_918_actual.ps1
"logginglogsuccess_918_actual : $LOGGINGLOGSUCCESS"
$PVTFIREWALLSTATE = C:\facts\pvtfirewallstate_921_actual.ps1
"pvtfirewallstate_921_actual : $PVTFIREWALLSTATE"
$PVTINBOUNDCONN = C:\facts\pvtinboundconn_922_actual.ps1
"pvtinboundconn_922_actual : $PVTINBOUNDCONN"
$PVTOUTBOUNDCONN = C:\facts\pvtoutboundconn_923_actual.ps1
"pvtoutboundconn_923_actual : $PVTOUTBOUNDCONN"
$PVTDISABLENOTIFICATION = C:\facts\pvtdisablenotification_924_actual.ps1
"pvtdisablenotification_924_actual : $PVTDISABLENOTIFICATION"
$PVTLOGGINGNAME = C:\facts\pvtloggingname_925_actual.ps1
"pvtloggingname_925_actual : $PVTLOGGINGNAME"
$PVTLOGGINGSIZELIMIT = C:\facts\pvtloggingsizelimit_926_actual.ps1
"pvtloggingsizelimit_926_actual : $PVTLOGGINGSIZELIMIT"
$PVTLOGGINGLOGDROPPACK = C:\facts\pvtlogginglogdroppack_927_actual.ps1
"pvtlogginglogdroppack_927_actual : $PVTLOGGINGLOGDROPPACK"
$PVTLOGGINGLOGSUCCESS = C:\facts\pvtlogginglogsuccess_928_actual.ps1
"pvtlogginglogsuccess_928_actual : $PVTLOGGINGLOGSUCCESS"
$PUBFIREWALLSTATE = C:\facts\pubfirewallstate_931_actual.ps1
"pubfirewallstate_931_actual : $PUBFIREWALLSTATE"
$PUBINBOUNDCONN = C:\facts\pubinboundconn_932_actual.ps1
"pubinboundconn_932_actual : $PUBINBOUNDCONN"
$PUBOUTBOUNDCONN = C:\facts\puboutboundconn_933_actual.ps1
"puboutboundconn_933_actual : $PUBOUTBOUNDCONN"
$PUBDISABLENOTIFICATION = C:\facts\pubdisablenotification_934_actual.ps1
"pubdisablenotification_934_actual : $PUBDISABLENOTIFICATION"
$LOCALFIREWALLRULES = C:\facts\localfirewallrules_935_actual.ps1
"localfirewallrules_935_actual : $LOCALFIREWALLRULES"
$LOCALCONNSECURULES = C:\facts\localconnsecurules_936_actual.ps1
"localconnsecurules_936_actual : $LOCALCONNSECURULES"
$PUBLOGGINGNAME = C:\facts\publoggingname_937_actual.ps1
"publoggingname_937_actual : $PUBLOGGINGNAME"
$PUBLOGGINGSIZELIMIT = C:\facts\publoggingsizelimit_938_actual.ps1
"publoggingsizelimit_938_actual : $PUBLOGGINGSIZELIMIT"
$PUBLOGGINGLOGDROPPACK = C:\facts\publogginglogdroppack_939_actual.ps1
"publogginglogdroppack_939_actual : $PUBLOGGINGLOGDROPPACK"
$PUBLOGGINGLOGSUCCESS = C:\facts\publogginglogsuccess_9310_actual.ps1
"publogginglogsuccess_9310_actual : $PUBLOGGINGLOGSUCCESS"
$AUDCREDVALIDATION = C:\facts\audcredvalidation_1711_actual.ps1
"audcredvalidation_1711_actual : $AUDCREDVALIDATION"
$AUDKERBEROSAUTHEN = C:\facts\audkerberosauthen_1712_actual.ps1
"audkerberosauthen_1712_actual : $AUDKERBEROSAUTHEN"
$AUDKERBEROSSRVTICK = C:\facts\audkerberossrvtick_1713_actual.ps1
"audkerberossrvtick_1713_actual : $AUDKERBEROSSRVTICK"
$AUDAPPGRPMANGMENT = C:\facts\audappgrpmangment_1721_actual.ps1
"audappgrpmangment_1721_actual : $AUDAPPGRPMANGMENT"
$AUDCOMPACCMANGMENT = C:\facts\audcompaccmangment_1722_actual.ps1
"audcompaccmangment_1722_actual : $AUDCOMPACCMANGMENT"
$AUDDISTRIBGRPMANGMENT = C:\facts\auddistribgrpmangment_1723_actual.ps1
"auddistribgrpmangment_1723_actual : $AUDDISTRIBGRPMANGMENT"
$AUDOTHERACCMANGMENT = C:\facts\audotheraccmangment_1724_actual.ps1
"audotheraccmangment_1724_actual : $AUDOTHERACCMANGMENT"
$AUDSECURGRPMANGMENT = C:\facts\audsecurgrpmangment_1725_actual.ps1
"audsecurgrpmangment_1725_actual : $AUDSECURGRPMANGMENT"
$AUDUSRACCMANGMENT = C:\facts\audusraccmangment_1726_actual.ps1
"audusraccmangment_1726_actual : $AUDUSRACCMANGMENT"
$AUDITPROCESSCREATION = C:\facts\auditprocesscreation_1731_actual.ps1
"auditprocesscreation_1731_actual : $AUDITPROCESSCREATION"
$AUDITDIRSERVACCESS = C:\facts\auditdirservaccess_1741_actual.ps1
"auditdirservaccess_1741_actual : $AUDITDIRSERVACCESS"
$AUDITDIRSERVCHG = C:\facts\auditdirservchg_1742_actual.ps1
"auditdirservchg_1742_actual : $AUDITDIRSERVCHG"
$AUDITACCLOCKOUT = C:\facts\auditacclockout_1751_actual.ps1
"auditacclockout_1751_actual : $AUDITACCLOCKOUT"
$AUDITLOGOFF = C:\facts\auditlogoff_1752_actual.ps1
"auditlogoff_1752_actual : $AUDITLOGOFF"
$AUDITLOGON = C:\facts\auditlogon_1753_actual.ps1
"auditlogon_1753_actual : $AUDITLOGON"
$AUDITOTHERLOGONOFF = C:\facts\auditotherlogonoff_1754_actual.ps1
"auditotherlogonoff_1754_actual : $AUDITOTHERLOGONOFF"
$AUDITSPECIALLOGON = C:\facts\auditspeciallogon_1755_actual.ps1
"auditspeciallogon_1755_actual : $AUDITSPECIALLOGON"
$AUDDTAILEDFILESHRE = C:\facts\auddtailedfileshre_1761_actual.ps1
"auddtailedfileshre_1761_actual : $AUDDTAILEDFILESHRE"
$AUDFILESHARE = C:\facts\audfileshare_1762_actual.ps1
"audfileshare_1762_actual : $AUDFILESHARE"
$AUDITOTHEROBJACCESS = C:\facts\auditotherobjaccess_1763_actual.ps1
"auditotherobjaccess_1763_actual : $AUDITOTHEROBJACCESS"
$AUDITREMOVABLESTORAGE = C:\facts\auditremovablestorage_1764_actual.ps1
"auditremovablestorage_1764_actual : $AUDITREMOVABLESTORAGE"
$AUDITPOLICYCHG = C:\facts\auditpolicychg_1771_actual.ps1
"auditpolicychg_1771_actual : $AUDITPOLICYCHG"
$AUDITAUTHENPOLICYCHG = C:\facts\auditauthenpolicychg_1772_actual.ps1
"auditauthenpolicychg_1772_actual : $AUDITAUTHENPOLICYCHG"
$AUDITAUTHORNPOLICYCHG = C:\facts\auditauthornpolicychg_1773_actual.ps1
"auditauthornpolicychg_1773_actual : $AUDITAUTHORNPOLICYCHG"
$AUDMPSSVCRULELEVELPOLICYCHG = C:\facts\audmpssvcrulelevelpolicychg_1774_actual.ps1
"audmpssvcrulelevelpolicychg_1774_actual : $AUDMPSSVCRULELEVELPOLICYCHG"
$AUDOTHRPOLICYCHG = C:\facts\audothrpolicychg_1775_actual.ps1
"audothrpolicychg_1775_actual : $AUDOTHRPOLICYCHG"
$AUDITSENSITIVEPRIVUSE = C:\facts\auditsensitiveprivuse_1781_actual.ps1
"auditsensitiveprivuse_1781_actual : $AUDITSENSITIVEPRIVUSE"
$AUDITIPSECDRIVER = C:\facts\auditipsecdriver_1791_actual.ps1
"auditipsecdriver_1791_actual : $AUDITIPSECDRIVER"
$AUDITOTHERSYSEVENTS = C:\facts\auditothersysevents_1792_actual.ps1
"auditothersysevents_1792_actual : $AUDITOTHERSYSEVENTS"
$AUDITSECURSTATECHG = C:\facts\auditsecurstatechg_1793_actual.ps1
"auditsecurstatechg_1793_actual : $AUDITSECURSTATECHG"
$AUDITSECURSYSEXT = C:\facts\auditsecursysext_1794_actual.ps1
"auditsecursysext_1794_actual : $AUDITSECURSYSEXT"
$AUDITSYSINTEGRITY = C:\facts\auditsysintegrity_1795_actual.ps1
"auditsysintegrity_1795_actual : $AUDITSYSINTEGRITY"
$ENABLELOCKSCREENCAM = C:\facts\enablelockscreencam_18111_actual.ps1
"enablelockscreencam_18111_actual : $ENABLELOCKSCREENCAM"
$ENABLELOCKSCREENSLIDE = C:\facts\enablelockscreenslide_18112_actual.ps1
"enablelockscreenslide_18112_actual : $ENABLELOCKSCREENSLIDE"
$CONFSMBCLIENT = C:\facts\confsmbclient_1832_actual.ps1
"confsmbclient_1832_actual : $CONFSMBCLIENT"
$CONFSMBSERVER = C:\facts\confsmbserver_1833_actual.ps1
"confsmbserver_1833_actual : $CONFSMBSERVER"
$ENABLESEHOP = C:\facts\enablesehop_1834_actual.ps1
"enablesehop_1834_actual : $ENABLESEHOP"
$ENABLEEXPROTLDAP = C:\facts\enableexprotldap_1835_actual.ps1
"enableexprotldap_1835_actual : $ENABLEEXPROTLDAP"
$NETBIOSNODETYPE = C:\facts\netbiosnodetype_1836_actual.ps1
"netbiosnodetype_1836_actual : $NETBIOSNODETYPE"
$WDIGESTAUTHEN = C:\facts\wdigestauthen_1837_actual.ps1
"wdigestauthen_1837_actual : $WDIGESTAUTHEN"
$AUTOLOGON = C:\facts\autologon_1841_actual.ps1
"autologon_1841_actual : $AUTOLOGON"
$IPSOURCEROUTING = C:\facts\ipsourcerouting_1842_actual.ps1
"ipsourcerouting_1842_actual : $IPSOURCEROUTING"
$IPSOURCEROUTPROTECT = C:\facts\ipsourceroutprotect_1843_actual.ps1
"ipsourceroutprotect_1843_actual : $IPSOURCEROUTPROTECT"
$ICMPREDIRECTS = C:\facts\icmpredirects_1844_actual.ps1
"icmpredirects_1844_actual : $ICMPREDIRECTS"
$KEEPALIVETIME = C:\facts\keepalivetime_1845_actual.ps1
"keepalivetime_1845_actual : $KEEPALIVETIME"
$NONAMERELEASE = C:\facts\nonamerelease_1846_actual.ps1
"nonamerelease_1846_actual : $NONAMERELEASE"
$PERFROUTDISCOVERY = C:\facts\perfroutdiscovery_1847_actual.ps1
"perfroutdiscovery_1847_actual : $PERFROUTDISCOVERY"
$SAFEDLLSEARCHMODE = C:\facts\safedllsearchmode_1848_actual.ps1
"safedllsearchmode_1848_actual : $SAFEDLLSEARCHMODE"
$SCREENSAVERTIME = C:\facts\screensavertime_1849_actual.ps1
"screensavertime_1849_actual : $SCREENSAVERTIME"
$TCPMAXDATARETRANSIPV6 = C:\facts\tcpmaxdataretransipv6_18410_actual.ps1
"tcpmaxdataretransipv6_18410_actual : $TCPMAXDATARETRANSIPV6"
$TCPMAXDATARETRANS = C:\facts\tcpmaxdataretrans_18411_actual.ps1
"tcpmaxdataretrans_18411_actual : $TCPMAXDATARETRANS"
$WARNINGLEVEL = C:\facts\warninglevel_18412_actual.ps1
"warninglevel_18412_actual : $WARNINGLEVEL"
$TURNOFFMULTICASTNAME = C:\facts\turnoffmulticastname_18541_actual.ps1
"turnoffmulticastname_18541_actual : $TURNOFFMULTICASTNAME"
$MAPPERIODRIVER = C:\facts\mapperiodriver_18591_actual.ps1
"mapperiodriver_18591_actual : $MAPPERIODRIVER"
$RESPONDERDRIVER = C:\facts\responderdriver_18592_actual.ps1
"responderdriver_18592_actual : $RESPONDERDRIVER"
$MSPEERNETSERV = C:\facts\mspeernetserv_185101_actual.ps1
"mspeernetserv_185101_actual : $MSPEERNETSERV"
$CONFNETBRIDGE = C:\facts\confnetbridge_185112_actual.ps1
"confnetbridge_185112_actual : $CONFNETBRIDGE"
$DOMAINUSRNETLOC = C:\facts\domainusrnetloc_185113_actual.ps1
"domainusrnetloc_185113_actual : $DOMAINUSRNETLOC"
$HARDENEDUNCPATH = C:\facts\hardeneduncpath_185141_actual.ps1
"hardeneduncpath_185141_actual : $HARDENEDUNCPATH"
$DISABLEIPV6 = C:\facts\disableipv6_1851921_actual.ps1
"disableipv6_1851921_actual : $DISABLEIPV6"
$CONFWIRELESSSET = C:\facts\confwirelessset_185201_actual.ps1
"confwirelessset_185201_actual : $CONFWIRELESSSET"
$WINSCONNECTNOWWIZ = C:\facts\winsconnectnowwiz_185202_actual.ps1
"winsconnectnowwiz_185202_actual : $WINSCONNECTNOWWIZ"
$MINIMIZEINETCONN = C:\facts\minimizeinetconn_185211_actual.ps1
"minimizeinetconn_185211_actual : $MINIMIZEINETCONN"
$OFFNOTIFNETUSAGE = C:\facts\offnotifnetusage_18711_actual.ps1
"offnotifnetusage_18711_actual : $OFFNOTIFNETUSAGE"
$CMDLINEPROCESSCREATE = C:\facts\cmdlineprocesscreate_18831_actual.ps1
"cmdlineprocesscreate_18831_actual : $CMDLINEPROCESSCREATE"
$ENCRYPTORACLEREM = C:\facts\encryptoraclerem_18841_actual.ps1
"encryptoraclerem_18841_actual : $ENCRYPTORACLEREM"
$NONEXPORTABLECRED = C:\facts\nonexportablecred_18842_actual.ps1
"nonexportablecred_18842_actual : $NONEXPORTABLECRED"
$BOOTSTARTDRIVPOLICY = C:\facts\bootstartdrivpolicy_188141_actual.ps1
"bootstartdrivpolicy_188141_actual : $BOOTSTARTDRIVPOLICY"
$REGPOLBACKGRDPROCESS = C:\facts\regpolbackgrdprocess_188211_actual.ps1
"regpolbackgrdprocess_188211_actual : $REGPOLBACKGRDPROCESS"
$REGPOLGRPPOLICYCHG = C:\facts\regpolgrppolicychg_188212_actual.ps1
"regpolgrppolicychg_188212_actual : $REGPOLGRPPOLICYCHG"
$BACKGRPREFRESH = C:\facts\backgrprefresh_188213_actual.ps1
"backgrprefresh_188213_actual : $BACKGRPREFRESH"
$TURNOFFPRINTDRIVER = C:\facts\turnoffprintdriver_1882211_actual.ps1
"turnoffprintdriver_1882211_actual : $TURNOFFPRINTDRIVER"
$TURNOFFDATASHARING = C:\facts\turnoffdatasharing_1882212_actual.ps1
"turnoffdatasharing_1882212_actual : $TURNOFFDATASHARING"
$TURNOFFERRORREPORT = C:\facts\turnofferrorreport_1882213_actual.ps1
"turnofferrorreport_1882213_actual : $TURNOFFERRORREPORT"
$TURNOFFINETCONNWIZ = C:\facts\turnoffinetconnwiz_1882214_actual.ps1
"turnoffinetconnwiz_1882214_actual : $TURNOFFINETCONNWIZ"
$TURNOFFINETDOWNLOAD = C:\facts\turnoffinetdownload_1882215_actual.ps1
"turnoffinetdownload_1882215_actual : $TURNOFFINETDOWNLOAD"
$TURNOFFPRINTING = C:\facts\turnoffprinting_1882216_actual.ps1
"turnoffprinting_1882216_actual : $TURNOFFPRINTING"
$TURNOFFREGISTRY = C:\facts\turnoffregistry_1882217_actual.ps1
"turnoffregistry_1882217_actual : $TURNOFFREGISTRY"
$TURNOFFSEARCHCOMP = C:\facts\turnoffsearchcomp_1882218_actual.ps1
"turnoffsearchcomp_1882218_actual : $TURNOFFSEARCHCOMP"
$TURNOFFORDERPRINTS = C:\facts\turnofforderprints_1882219_actual.ps1
"turnofforderprints_1882219_actual : $TURNOFFORDERPRINTS"
$TURNOFFPUBLISHWEB = C:\facts\turnoffpublishweb_18822110_actual.ps1
"turnoffpublishweb_18822110_actual : $TURNOFFPUBLISHWEB"
$TURNOFFWMCEIP = C:\facts\turnoffwmceip_18822111_actual.ps1
"turnoffwmceip_18822111_actual : $TURNOFFWMCEIP"
$TURNOFFWCEIP = C:\facts\turnoffwceip_18822112_actual.ps1
"turnoffwceip_18822112_actual : $TURNOFFWCEIP"
$TURNOFFWINERROREP = C:\facts\turnoffwinerrorep_18822113_actual.ps1
"turnoffwinerrorep_18822113_actual : $TURNOFFWINERROREP"
$DISALLOWCOPYUSRINPUT = C:\facts\disallowcopyusrinput_188271_actual.ps1
"disallowcopyusrinput_188271_actual : $DISALLOWCOPYUSRINPUT"
$DONTDISPLAYNETUI = C:\facts\dontdisplaynetui_188281_actual.ps1
"dontdisplaynetui_188281_actual : $DONTDISPLAYNETUI"
$DONTENUMCONNUSR = C:\facts\dontenumconnusr_188282_actual.ps1
"dontenumconnusr_188282_actual : $DONTENUMCONNUSR"
$TURNOFFAPPNOTFIC = C:\facts\turnoffappnotfic_188284_actual.ps1
"turnoffappnotfic_188284_actual : $TURNOFFAPPNOTFIC"
$TURNOFFPICPWDSIGNIN = C:\facts\turnoffpicpwdsignin_188285_actual.ps1
"turnoffpicpwdsignin_188285_actual : $TURNOFFPICPWDSIGNIN"
$TURNOFFPINSIGNIN = C:\facts\turnoffpinsignin_188286_actual.ps1
"turnoffpinsignin_188286_actual : $TURNOFFPINSIGNIN"
$PWDCOMPWAKESONBATTERY = C:\facts\pwdcompwakesonbattery_1883461_actual.ps1
"pwdcompwakesonbattery_1883461_actual : $PWDCOMPWAKESONBATTERY"
$PWDCOMPWAKESPLUGGEDIN = C:\facts\pwdcompwakespluggedin_1883462_actual.ps1
"pwdcompwakespluggedin_1883462_actual : $PWDCOMPWAKESPLUGGEDIN"
$CONFOFFERREMOTEASSIST = C:\facts\confofferremoteassist_188361_actual.ps1
"confofferremoteassist_188361_actual : $CONFOFFERREMOTEASSIST"
$CONFSOLICREMOTEASSIST = C:\facts\confsolicremoteassist_188362_actual.ps1
"confsolicremoteassist_188362_actual : $CONFSOLICREMOTEASSIST"
$MSDIAGNOSTICTOOL = C:\facts\msdiagnostictool_1884751_actual.ps1
"msdiagnostictool_1884751_actual : $MSDIAGNOSTICTOOL"
$PERFTRACK = C:\facts\perftrack_18847111_actual.ps1
"perftrack_18847111_actual : $PERFTRACK"
$TURNOFFADVERTID = C:\facts\turnoffadvertid_188491_actual.ps1
"turnoffadvertid_188491_actual : $TURNOFFADVERTID"
$ENABLEWINNTPCLI = C:\facts\enablewinntpcli_1885211_actual.ps1
"enablewinntpcli_1885211_actual : $ENABLEWINNTPCLI"
$ALLOWMSACC = C:\facts\allowmsacc_18961_actual.ps1
"allowmsacc_18961_actual : $ALLOWMSACC"
$AUTOPLAYNONVOLDEV = C:\facts\autoplaynonvoldev_18981_actual.ps1
"autoplaynonvoldev_18981_actual : $AUTOPLAYNONVOLDEV"
$DEFAULTAUTORUN = C:\facts\defaultautorun_18982_actual.ps1
"defaultautorun_18982_actual : $DEFAULTAUTORUN"
$TURNOFFAUTOPLAY = C:\facts\turnoffautoplay_18983_actual.ps1
"turnoffautoplay_18983_actual : $TURNOFFAUTOPLAY"
$PWDREVEALBUTTON = C:\facts\pwdrevealbutton_189151_actual.ps1
"pwdrevealbutton_189151_actual : $PWDREVEALBUTTON"
$ADMACCELEVATION = C:\facts\admaccelevation_189152_actual.ps1
"admaccelevation_189152_actual : $ADMACCELEVATION"
$EMET = C:\facts\emet_189241_actual.ps1
"emet_189241_actual : $EMET"
$ENMITIGATIONSETTING = C:\facts\enmitigationsetting_189242_actual.ps1
"enmitigationsetting_189242_actual : $ENMITIGATIONSETTING"
$ENDEFAULTIE = C:\facts\endefaultie_189243_actual.ps1
"endefaultie_189243_actual : $ENDEFAULTIE"
$ENDEFPOPSOFTWARE = C:\facts\endefpopsoftware_189244_actual.ps1
"endefpopsoftware_189244_actual : $ENDEFPOPSOFTWARE"
$ENDEFRECSOFWARE = C:\facts\endefrecsofware_189245_actual.ps1
"endefrecsofware_189245_actual : $ENDEFRECSOFWARE"
$ENAPPOPTINASLR = C:\facts\enappoptinaslr_189246_actual.ps1
"enappoptinaslr_189246_actual : $ENAPPOPTINASLR"
$ENAPPOPTOUTDEP = C:\facts\enappoptoutdep_189247_actual.ps1
"enappoptoutdep_189247_actual : $ENAPPOPTOUTDEP"
$ENAPPOPTOUTSEHOP = C:\facts\enappoptoutsehop_189248_actual.ps1
"enappoptoutsehop_189248_actual : $ENAPPOPTOUTSEHOP"
$APPCONTROLEVENTLOG = C:\facts\appcontroleventlog_1892611_actual.ps1
"appcontroleventlog_1892611_actual : $APPCONTROLEVENTLOG"
$APPMAXLOGFILESIZE = C:\facts\appmaxlogfilesize_1892612_actual.ps1
"appmaxlogfilesize_1892612_actual : $APPMAXLOGFILESIZE"
$SECURCONTROLEVENTLOG = C:\facts\securcontroleventlog_1892621_actual.ps1
"securcontroleventlog_1892621_actual : $SECURCONTROLEVENTLOG"
$SECURMAXLOGFILESIZE = C:\facts\securmaxlogfilesize_1892622_actual.ps1
"securmaxlogfilesize_1892622_actual : $SECURMAXLOGFILESIZE"
$SETUPCONTROLEVENTLOG = C:\facts\setupcontroleventlog_1892631_actual.ps1
"setupcontroleventlog_1892631_actual : $SETUPCONTROLEVENTLOG"
$SETUPMAXLOGFILESIZE = C:\facts\setupmaxlogfilesize_1892632_actual.ps1
"setupmaxlogfilesize_1892632_actual : $SETUPMAXLOGFILESIZE"
$SYSCONTROLEVENTLOG = C:\facts\syscontroleventlog_1892641_actual.ps1
"syscontroleventlog_1892641_actual : $SYSCONTROLEVENTLOG"
$SYSMAXLOGFILESIZE = C:\facts\sysmaxlogfilesize_1892642_actual.ps1
"sysmaxlogfilesize_1892642_actual : $SYSMAXLOGFILESIZE"
$TURNOFFDATAEXEC = C:\facts\turnoffdataexec_189302_actual.ps1
"turnoffdataexec_189302_actual : $TURNOFFDATAEXEC"
$TURNOFFHEAPTERMINATION = C:\facts\turnoffheaptermination_189303_actual.ps1
"turnoffheaptermination_189303_actual : $TURNOFFHEAPTERMINATION"
$TURNOFFSHELLPROTOCOL = C:\facts\turnoffshellprotocol_189304_actual.ps1
"turnoffshellprotocol_189304_actual : $TURNOFFSHELLPROTOCOL"
$OFFWINLOCPROVIDER = C:\facts\offwinlocprovider_1893911_actual.ps1
"offwinlocprovider_1893911_actual : $OFFWINLOCPROVIDER"
$TURNOFFLOCATION = C:\facts\turnofflocation_189392_actual.ps1
"turnofflocation_189392_actual : $TURNOFFLOCATION"
$PREVENTONEDRIVEUSAGE = C:\facts\preventonedriveusage_189521_actual.ps1
"preventonedriveusage_189521_actual : $PREVENTONEDRIVEUSAGE"
$PREVENTONEDRIVEWIN81 = C:\facts\preventonedrivewin81_189522_actual.ps1
"preventonedrivewin81_189522_actual : $PREVENTONEDRIVEWIN81"
$DONTALLOWPWDSAVED = C:\facts\dontallowpwdsaved_1895922_actual.ps1
"dontallowpwdsaved_1895922_actual : $DONTALLOWPWDSAVED"
$RESTRICTREMDESKTOPSERV = C:\facts\restrictremdesktopserv_18959321_actual.ps1
"restrictremdesktopserv_18959321_actual : $RESTRICTREMDESKTOPSERV"
$DONTALLOWCOMPORT = C:\facts\dontallowcomport_18959331_actual.ps1
"dontallowcomport_18959331_actual : $DONTALLOWCOMPORT"
$DONTALLOWDRIVE = C:\facts\dontallowdrive_18959332_actual.ps1
"dontallowdrive_18959332_actual : $DONTALLOWDRIVE"
$DONTALLOWLPTPORT = C:\facts\dontallowlptport_18959333_actual.ps1
"dontallowlptport_18959333_actual : $DONTALLOWLPTPORT"
$DONTALLOWPLUGPLAYDEV = C:\facts\dontallowplugplaydev_18959334_actual.ps1
"dontallowplugplaydev_18959334_actual : $DONTALLOWPLUGPLAYDEV"
$PWDPROMPT = C:\facts\pwdprompt_18959391_actual.ps1
"pwdprompt_18959391_actual : $PWDPROMPT"
$SECURERPCCOMMUNIC = C:\facts\securerpccommunic_18959392_actual.ps1
"securerpccommunic_18959392_actual : $SECURERPCCOMMUNIC"
$ENABLERDPSSL = C:\facts\enablerdpssl_18959393_actual.ps1
"enablerdpssl_18959393_actual : $ENABLERDPSSL"
$ENNETLEVELAUTH = C:\facts\ennetlevelauth_18959394_actual.ps1
"ennetlevelauth_18959394_actual : $ENNETLEVELAUTH"
$SETCLIENTCONN = C:\facts\setclientconn_18959395_actual.ps1
"setclientconn_18959395_actual : $SETCLIENTCONN"
$TIMELIMITACTIVE = C:\facts\timelimitactive_189593101_actual.ps1
"timelimitactive_189593101_actual : $TIMELIMITACTIVE"
$TIMELIMITDISCONSESSION = C:\facts\timelimitdisconsession_189593102_actual.ps1
"timelimitdisconsession_189593102_actual : $TIMELIMITDISCONSESSION"
$DONTDELTEMPFOLDER = C:\facts\dontdeltempfolder_189593111_actual.ps1
"dontdeltempfolder_189593111_actual : $DONTDELTEMPFOLDER"
$DONTUSETEMPFOLDER = C:\facts\dontusetempfolder_189593112_actual.ps1
"dontusetempfolder_189593112_actual : $DONTUSETEMPFOLDER"
$PREVENTDOWNLOAD = C:\facts\preventdownload_189601_actual.ps1
"preventdownload_189601_actual : $PREVENTDOWNLOAD"
$ALLOWINDEXENCRYPFILE = C:\facts\allowindexencrypfile_189612_actual.ps1
"allowindexencrypfile_189612_actual : $ALLOWINDEXENCRYPFILE"
$SETSHAREDINFO = C:\facts\setsharedinfo_189613_actual.ps1
"setsharedinfo_189613_actual : $SETSHAREDINFO"
$TURNOFFKMSCLIONLINE = C:\facts\turnoffkmsclionline_189661_actual.ps1
"turnoffkmsclionline_189661_actual : $TURNOFFKMSCLIONLINE"
$CONFMSMAPS = C:\facts\confmsmaps_1897731_actual.ps1
"confmsmaps_1897731_actual : $CONFMSMAPS"
$JOINMSMAPS = C:\facts\joinmsmaps_1897732_actual.ps1
"joinmsmaps_1897732_actual : $JOINMSMAPS"
$TURNONMONITORING = C:\facts\turnonmonitoring_1897771_actual.ps1
"turnonmonitoring_1897771_actual : $TURNONMONITORING"
$CONFWATSONEVENTS = C:\facts\confwatsonevents_1897791_actual.ps1
"confwatsonevents_1897791_actual : $CONFWATSONEVENTS"
$SCANREMOVABLEDRIVER = C:\facts\scanremovabledriver_18977101_actual.ps1
"scanremovabledriver_18977101_actual : $SCANREMOVABLEDRIVER"
$TURNONEMAILSCAN = C:\facts\turnonemailscan_18977102_actual.ps1
"turnonemailscan_18977102_actual : $TURNONEMAILSCAN"
$TURNOFFWINDEFENDERANTIVIRUS = C:\facts\turnoffwindefenderantivirus_1897714_actual.ps1
"turnoffwindefenderantivirus_1897714_actual : $TURNOFFWINDEFENDERANTIVIRUS"
$CONFWINDEFENDSMARTSCREEN = C:\facts\confwindefendsmartscreen_1898011_actual.ps1
"confwindefendsmartscreen_1898011_actual : $CONFWINDEFENDSMARTSCREEN"
$CONFDEFAULTCONSENT = C:\facts\confdefaultconsent_1898121_actual.ps1
"confdefaultconsent_1898121_actual : $CONFDEFAULTCONSENT"
$DISABMEMDUMPREP = C:\facts\disabmemdumprep_189813_actual.ps1
"disabmemdumprep_189813_actual : $DISABMEMDUMPREP"
$ALLOWUSRCONTROL = C:\facts\allowusrcontrol_189851_actual.ps1
"allowusrcontrol_189851_actual : $ALLOWUSRCONTROL"
$ELEVATEDPRIVIL = C:\facts\elevatedprivil_189852_actual.ps1
"elevatedprivil_189852_actual : $ELEVATEDPRIVIL"
$PREVIESECURPROMPT = C:\facts\previesecurprompt_189853_actual.ps1
"previesecurprompt_189853_actual : $PREVIESECURPROMPT"
$SIGNINLASTINTERACTIVEUSR = C:\facts\signinlastinteractiveusr_189861_actual.ps1
"signinlastinteractiveusr_189861_actual : $SIGNINLASTINTERACTIVEUSR"
$PSHELLSCRIPTBLOCKLOG = C:\facts\pshellscriptblocklog_189951_actual.ps1
"pshellscriptblocklog_189951_actual : $PSHELLSCRIPTBLOCKLOG"
$PSHELLTRANSCRIPTION = C:\facts\pshelltranscription_189952_actual.ps1
"pshelltranscription_189952_actual : $PSHELLTRANSCRIPTION"
$ALLOWBASICAUTHEN = C:\facts\allowbasicauthen_1899711_actual.ps1
"allowbasicauthen_1899711_actual : $ALLOWBASICAUTHEN"
$ALLOWUNENCRYPTRAFFIC = C:\facts\allowunencryptraffic_1899712_actual.ps1
"allowunencryptraffic_1899712_actual : $ALLOWUNENCRYPTRAFFIC"
$DISALLOWDIGESTAUTHEN = C:\facts\disallowdigestauthen_1899713_actual.ps1
"disallowdigestauthen_1899713_actual : $DISALLOWDIGESTAUTHEN"
$WINRMALLOWBASICAUTHEN = C:\facts\winrmallowbasicauthen_1899721_actual.ps1
"winrmallowbasicauthen_1899721_actual : $WINRMALLOWBASICAUTHEN"
$ALLOWREMOTESERVMANAGMENT = C:\facts\allowremoteservmanagment_1899722_actual.ps1
"allowremoteservmanagment_1899722_actual : $ALLOWREMOTESERVMANAGMENT"
$WINRMALLOWENCRYPTRAFFIC = C:\facts\winrmallowencryptraffic_1899723_actual.ps1
"winrmallowencryptraffic_1899723_actual : $WINRMALLOWENCRYPTRAFFIC"
$DISALLOWWINRM = C:\facts\disallowwinrm_1899724_actual.ps1
"disallowwinrm_1899724_actual : $DISALLOWWINRM"
$ALLOWREMOTESHELLACCESS = C:\facts\allowremoteshellaccess_189981_actual.ps1
"allowremoteshellaccess_189981_actual : $ALLOWREMOTESHELLACCESS"
$CONFAUTOUPDATES = C:\facts\confautoupdates_1891021_actual.ps1
"confautoupdates_1891021_actual : $CONFAUTOUPDATES"
$CONFAUTOUPDATESDAY = C:\facts\confautoupdatesday_1891022_actual.ps1
"confautoupdatesday_1891022_actual : $CONFAUTOUPDATESDAY"
$NOAUTORESTART = C:\facts\noautorestart_1891023_actual.ps1
"noautorestart_1891023_actual : $NOAUTORESTART"
$ENABLESCRNSAV = C:\facts\enablescrnsav_19131_actual.ps1
"enablescrnsav_19131_actual : $ENABLESCRNSAV"
$FORSPECSCRNSAV = C:\facts\forspecscrnsav_19132_actual.ps1
"forspecscrnsav_19132_actual : $FORSPECSCRNSAV"
$PASSPROSCRNSAV = C:\facts\passproscrnsav_19133_actual.ps1
"passproscrnsav_19133_actual : $PASSPROSCRNSAV"
$SCRNSAVTIMEOUT = C:\facts\scrnsavtimeout_19134_actual.ps1
"scrnsavtimeout_19134_actual : $SCRNSAVTIMEOUT"
$TOASTNOTIFLOCKSCRN = C:\facts\toastnotiflockscrn_19511_actual.ps1
"toastnotiflockscrn_19511_actual : $TOASTNOTIFLOCKSCRN"
$HELPEXPIMPROGRM = C:\facts\helpexpimprogram_196611_actual.ps1
"helpexpimprogram_196611_actual : $HELPEXPIMPROGRM"
$PREZONEINFILE = C:\facts\prezoneinfile_19741_actual.ps1
"prezoneinfile_19741_actual : $PREZONEINFILE"
$NOTIFYANTIPROGRAMPEN = C:\facts\notifyantiprogramopen_19742_actual.ps1
"notifyantiprogramopen_19742_actual : $NOTIFYANTIPROGRAMPEN"
$PREVUSERSHARPROF = C:\facts\prevusersharprof_197261_actual.ps1
"prevusersharprof_197261_actual : $PREVUSERSHARPROF"
$INSTALLELEVPRIVILEG = C:\facts\installelevprivileg_197411_actual.ps1
"installelevprivileg_197411_actual : $INSTALLELEVPRIVILEG"
$PREVCODECDOWN = C:\facts\prevcodecdown_1974521_actual.ps1
"prevcodecdown_1974521_actual : $PREVCODECDOWN"