$ENFPWDHIST = C:\facts\enfpwdhist_111_actual.ps1
"enfpwdhist_111_actual : $ENFPWDHIST"
$MAXPWDAGE = C:\facts\maxpwdage_112_actual.ps1
"maxpwdage_112_actual : $MAXPWDAGE"
$MINPWDAGE = C:\facts\minpwdage_113_actual.ps1
"minpwdage_113_actual : $MINPWDAGE"
$MINPWDLEN = C:\facts\minpwdlen_114_actual.ps1
"minpwdlen_114_actual : $MINPWDLEN"
$PWDCOMPLEX = C:\facts\pwdcomplex_115_actual.ps1
"pwdcomplex_115_actual : $PWDCOMPLEX"
$REVERSEPATH = C:\facts\reversepath_116_actual.ps1
"reversepath_116_actual : $REVERSEPATH"
$ACCLOCKDUR = C:\facts\acclockdur_121_actual.ps1
"acclockdur_121_actual : $ACCLOCKDUR"
$ACCLOCKTHRES = C:\facts\acclockthres_122_actual.ps1
"acclockthres_122_actual : $ACCLOCKTHRES"
$RESETACCLOCK = C:\facts\resetacclock_123_actual.ps1
"resetacclock_123_actual : $RESETACCLOCK"
$ACCESSCREDMGR = C:\facts\accesscredmgr_221_actual.ps1
"accesscredmgr_221_actual : $ACCESSCREDMGR"
$ACCESSCOMPMS = C:\facts\accesscompms_223_actual.ps1
"accesscompms_223_actual : $ACCESSCOMPMS"
$ACTASOS = C:\facts\actasos_224_actual.ps1
"actasos_224_actual : $ACTASOS"
$MEMQUOTAPROCESS = C:\facts\memquotaprocess_226_actual.ps1
"memquotaprocess_226_actual : $MEMQUOTAPROCESS"
$ALLOWLOGLOCAL = C:\facts\allowloglocal_227_actual.ps1
"allowloglocal_227_actual : $ALLOWLOGLOCAL"
$ALLOWLOGREMDESKMS = C:\facts\allowlogremdeskms_229_actual.ps1
"allowlogremdeskms_229_actual : $ALLOWLOGREMDESKMS"
$BACKUPFILEDIRS = C:\facts\backupfiledirs_2210_actual.ps1
"backupfiledirs_2210_actual : $BACKUPFILEDIRS"
$CHGSYSTIME = C:\facts\chgsystime_2211_actual.ps1
"chgsystime_2211_actual : $CHGSYSTIME"
$CHGTIMEZONE = C:\facts\chgtimezone_2212_actual.ps1
"chgtimezone_2212_actual : $CHGTIMEZONE"
$PAGEFILE = C:\facts\pagefile_2213_actual.ps1
"pagefile_2213_actual : $PAGEFILE"
$TOKENOBJ = C:\facts\tokenobj_2214_actual.ps1
"tokenobj_2214_actual : $TOKENOBJ"
$GLOBALOBJ = C:\facts\globalobj_2215_actual.ps1
"globalobj_2215_actual : $GLOBALOBJ"
$PERMSHAREDOBJ = C:\facts\permsharedobj_2216_actual.ps1
"permsharedobj_2216_actual : $PERMSHAREDOBJ"
$SYSBOLICLINKSMS = C:\facts\sysboliclinksms_2218_actual.ps1
"sysboliclinksms_2218_actual : $SYSBOLICLINKSMS"
$DEBUGPROG = C:\facts\debugprog_2219_actual.ps1
"debugprog_2219_actual : $DEBUGPROG"
$DENYACCESSMS = C:\facts\denyaccessms_2221_actual.ps1
"denyaccessms_2221_actual : $DENYACCESSMS"
$DENYLOGBATCHJOB = C:\facts\denylogbatchjob_2222_actual.ps1
"denylogbatchjob_2222_actual : $DENYLOGBATCHJOB"
$DENYLOGSERVICE = C:\facts\denylogservice_2223_actual.ps1
"denylogservice_2223_actual : $DENYLOGSERVICE"
$DENYLOGLOCALLY = C:\facts\denyloglocally_2224_actual.ps1
"denyloglocally_2224_actual : $DENYLOGLOCALLY"
$DENYLOGREMDESKMS = C:\facts\denylogremdeskms_2226_actual.ps1
"denylogremdeskms_2226_actual : $DENYLOGREMDESKMS"
$ENBCOMPUSRACCMS = C:\facts\enbcompusraccms_2228_actual.ps1
"enbcompusraccms_2228_actual : $ENBCOMPUSRACCMS"
$FORCESHUTDOWN = C:\facts\forceshutdown_2229_actual.ps1
"forceshutdown_2229_actual : $FORCESHUTDOWN"
$SECURITYAUDITS = C:\facts\securityaudits_2230_actual.ps1
"securityaudits_2230_actual : $SECURITYAUDITS"
$CLIENTAUTHENMS = C:\facts\clientauthenms_2232_actual.ps1
"clientauthenms_2232_actual : $CLIENTAUTHENMS"
$INCSCHEDPRIOR = C:\facts\incschedprior_2233_actual.ps1
"incschedprior_2233_actual : $INCSCHEDPRIOR"
$LOADUNLOADDEVDRIVER = C:\facts\loadunloaddevdriver_2234_actual.ps1
"loadunloaddevdriver_2234_actual : $LOADUNLOADDEVDRIVER"
$LOCKPAGEMEM = C:\facts\lockpagemem_2235_actual.ps1
"lockpagemem_2235_actual : $LOCKPAGEMEM"
$AUDSECURLOGMS = C:\facts\audsecurlogms_2238_actual.ps1
"audsecurlogms_2238_actual : $AUDSECURLOGMS"
$MODOBJLABEL = C:\facts\modobjlabel_2239_actual.ps1
"modobjlabel_2239_actual : $MODOBJLABEL"
$MODFIRMENV = C:\facts\modfirmenv_2240_actual.ps1
"modfirmenv_2240_actual : $MODFIRMENV"
$VOLMAINTASKS = C:\facts\volmaintasks_2241_actual.ps1
"volmaintasks_2241_actual : $VOLMAINTASKS"
$PROFSINGLEPRO = C:\facts\profsinglepro_2242_actual.ps1
"profsinglepro_2242_actual : $PROFSINGLEPRO"
$PROFSYSPERF = C:\facts\profsysperf_2243_actual.ps1
"profsysperf_2243_actual : $PROFSYSPERF"
$REPLPROTOKEN = C:\facts\replprotoken_2244_actual.ps1
"replprotoken_2244_actual : $REPLPROTOKEN"
$RESTOREFILEDIRS = C:\facts\restorefiledirs_2245_actual.ps1
"restorefiledirs_2245_actual : $RESTOREFILEDIRS"
$SHUTDOWNSYS = C:\facts\shutdownsys_2246_actual.ps1
"shutdownsys_2246_actual : $SHUTDOWNSYS"
$OWNERSHIPFILE = C:\facts\ownershipfile_2248_actual.ps1
"ownershipfile_2248_actual : $OWNERSHIPFILE"
$ADMACCSTAT = C:\facts\admaccstat_2311_actual.ps1
"admaccstat_2311_actual : $ADMACCSTAT"
$BLOCKMSACC = C:\facts\blockmsacc_2312_actual.ps1
"blockmsacc_2312_actual : $BLOCKMSACC"
$GUESTACCSTAT = C:\facts\guestaccstat_2313_actual.ps1
"guestaccstat_2313_actual : $GUESTACCSTAT"
$LIMITLOCACCUSE = C:\facts\limitlocaccuse_2314_actual.ps1
"limitlocaccuse_2314_actual : $LIMITLOCACCUSE"
$RENAMEADMACC = C:\facts\renameadmacc_2315_actual.ps1
"renameadmacc_2315_actual : $RENAMEADMACC"
$RENAMEGUESTACC = C:\facts\renameguestacc_2316_actual.ps1
"renameguestacc_2316_actual : $RENAMEGUESTACC"
$FORCEAUDPOLICY = C:\facts\forceaudpolicy_2321_actual.ps1
"forceaudpolicy_2321_actual : $FORCEAUDPOLICY"
$SYSSHUTDOWNSECURAUD = C:\facts\sysshutdownsecuraud_2322_actual.ps1
"sysshutdownsecuraud_2322_actual : $SYSSHUTDOWNSECURAUD"
$ALLOWREMOVMEDIA = C:\facts\allowremovmedia_2341_actual.ps1
"allowremovmedia_2341_actual : $ALLOWREMOVMEDIA"
$PREVENTUSR = C:\facts\preventusr_2342_actual.ps1
"preventusr_2342_actual : $PREVENTUSR"
$DIGIENCRYPTSIGN = C:\facts\digiencryptsign_2361_actual.ps1
"digiencryptsign_2361_actual : $DIGIENCRYPTSIGN"
$DIGIENCRYPSECDATA = C:\facts\digiencrypsecdata_2362_actual.ps1
"digiencrypsecdata_2362_actual : $DIGIENCRYPSECDATA"
$DIGISIGNSECDATA = C:\facts\digisignsecdata_2363_actual.ps1
"digisignsecdata_2363_actual : $DIGISIGNSECDATA"
$DISMACHACCPWDCHG = C:\facts\dismachaccpwdchg_2364_actual.ps1
"dismachaccpwdchg_2364_actual : $DISMACHACCPWDCHG"
$MAXMACHACCPWDAGE = C:\facts\maxmachaccpwdage_2365_actual.ps1
"maxmachaccpwdage_2365_actual : $MAXMACHACCPWDAGE"
$REQSESSIONKEY = C:\facts\reqsessionkey_2366_actual.ps1
"reqsessionkey_2366_actual : $REQSESSIONKEY"
$DONTREQCTRLALTDEL = C:\facts\dontreqctrlaltdel_2371_actual.ps1
"dontreqctrlaltdel_2371_actual : $DONTREQCTRLALTDEL"
$DONTDISPLASTUSRNAME = C:\facts\dontdisplastusrname_2372_actual.ps1
"dontdisplastusrname_2372_actual : $DONTDISPLASTUSRNAME"
$MACHINACTLIMIT = C:\facts\machinactlimit_2373_actual.ps1
"machinactlimit_2373_actual : $MACHINACTLIMIT"
$MSGTEXTUSR = C:\facts\msgtextusr_2374_actual.ps1
"msgtextusr_2374_actual : $MSGTEXTUSR"
$MSGTITLEUSR = C:\facts\msgtitleusr_2375_actual.ps1
"msgtitleusr_2375_actual : $MSGTITLEUSR"
$COUNTPREVLOGONS = C:\facts\countprevlogons_2376_actual.ps1
"countprevlogons_2376_actual : $COUNTPREVLOGONS"
$PROMPTUSRCHGPWD = C:\facts\promptusrchgpwd_2377_actual.ps1
"promptusrchgpwd_2377_actual : $PROMPTUSRCHGPWD"
$DCAUTHENUNLOCKWS = C:\facts\dcauthenunlockws_2378_actual.ps1
"dcauthenunlockws_2378_actual : $DCAUTHENUNLOCKWS"
$SMARTCARDREMOVAL = C:\facts\smartcardremoval_2379_actual.ps1
"smartcardremoval_2379_actual : $SMARTCARDREMOVAL"
$DIGISIGNCLIENT = C:\facts\digisignclient_2381_actual.ps1
"digisignclient_2381_actual : $DIGISIGNCLIENT"
$DIGISIGNSERVAGREE = C:\facts\digisignservagree_2382_actual.ps1
"digisignservagree_2382_actual : $DIGISIGNSERVAGREE"
$SENDUNENCRYPPWD = C:\facts\sendunencryppwd_2383_actual.ps1
"sendunencryppwd_2383_actual : $SENDUNENCRYPPWD"
$SETIDLETIME = C:\facts\setidletime_2391_actual.ps1
"setidletime_2391_actual : $SETIDLETIME"
$DIGISIGNSERV = C:\facts\digisignserv_2392_actual.ps1
"digisignserv_2392_actual : $DIGISIGNSERV"
$DIGISIGNCLIAGREE = C:\facts\digisigncliagree_2393_actual.ps1
"digisigncliagree_2393_actual : $DIGISIGNCLIAGREE"
$DISCONCLILOGONHREXP = C:\facts\disconclilogonhrexp_2394_actual.ps1
"disconclilogonhrexp_2394_actual : $DISCONCLILOGONHREXP"
$SPNNAMEVALIDATION = C:\facts\spnnamevalidation_2395_actual.ps1
"spnnamevalidation_2395_actual : $SPNNAMEVALIDATION"
$ALLOWANONYSID = C:\facts\allowanonysid_23101_actual.ps1
"allowanonysid_23101_actual : $ALLOWANONYSID"
$DONTALLOWANONYSAMACC = C:\facts\dontallowanonysamacc_23102_actual.ps1
"dontallowanonysamacc_23102_actual : $DONTALLOWANONYSAMACC"
$DONTALLOWANONYSAMACCSHARES = C:\facts\dontallowanonysamaccshares_23103_actual.ps1
"dontallowanonysamaccshares_23103_actual : $DONTALLOWANONYSAMACCSHARES"
$DONTALLOWSTORAGEPWDCRED = C:\facts\dontallowstoragepwdcred_23104_actual.ps1
"dontallowstoragepwdcred_23104_actual : $DONTALLOWSTORAGEPWDCRED"
$ANONYUSRPERM = C:\facts\anonyusrperm_23105_actual.ps1
"anonyusrperm_23105_actual : $ANONYUSRPERM"
$NAMEDPIPESMS = C:\facts\namedpipesms_23107_actual.ps1
"namedpipesms_23107_actual : $NAMEDPIPESMS"
$REMOTEACCESREGPATH = C:\facts\remoteaccesregpath_23108_actual.ps1
"remoteaccesregpath_23108_actual : $REMOTEACCESREGPATH"
$REMOTEACCESREGSUBPATH = C:\facts\remoteaccesregsubpath_23109_actual.ps1
"remoteaccesregsubpath_23109_actual : $REMOTEACCESREGSUBPATH"
$RESTRICTANONYACCES = C:\facts\restrictanonyacces_231010_actual.ps1
"restrictanonyacces_231010_actual : $RESTRICTANONYACCES"
$RESTRICTCLITOSAM = C:\facts\restrictclitosam_231011_actual.ps1
"restrictclitosam_231011_actual : $RESTRICTCLITOSAM"
$SHARESACCESS = C:\facts\sharesaccess_231012_actual.ps1
"sharesaccess_231012_actual : $SHARESACCESS"
$SHARESECURLOCALACC = C:\facts\sharesecurlocalacc_231013_actual.ps1
"sharesecurlocalacc_231013_actual : $SHARESECURLOCALACC"
$ALLOWLOCALSYS = C:\facts\allowlocalsys_23111_actual.ps1
"allowlocalsys_23111_actual : $ALLOWLOCALSYS"
$ALLOWLOCALSYSNULL = C:\facts\allowlocalsysnull_23112_actual.ps1
"allowlocalsysnull_23112_actual : $ALLOWLOCALSYSNULL"
$ALLOWPKU2UAUTHEN = C:\facts\allowpku2uauthen_23113_actual.ps1
"allowpku2uauthen_23113_actual : $ALLOWPKU2UAUTHEN"
$KERBEROSENCRYP = C:\facts\kerberosencryp_23114_actual.ps1
"kerberosencryp_23114_actual : $KERBEROSENCRYP"
$DONTSTORELANHASHVAL = C:\facts\dontstorelanhashval_23115_actual.ps1
"dontstorelanhashval_23115_actual : $DONTSTORELANHASHVAL"
$FORCELOGOFF = C:\facts\forcelogoff_23116_actual.ps1
"forcelogoff_23116_actual : $FORCELOGOFF"
$LANMGRAUTHEN = C:\facts\lanmgrauthen_23117_actual.ps1
"lanmgrauthen_23117_actual : $LANMGRAUTHEN"
$LDAPCLISIGN = C:\facts\ldapclisign_23118_actual.ps1
"ldapclisign_23118_actual : $LDAPCLISIGN"
$MINSESSIONSECURCLI = C:\facts\minsessionsecurcli_23119_actual.ps1
"minsessionsecurcli_23119_actual : $MINSESSIONSECURCLI"
$MINSESSIONSECURSERV = C:\facts\minsessionsecurserv_231110_actual.ps1
"minsessionsecurserv_231110_actual : $MINSESSIONSECURSERV"
$ALLOWSYSSHUTDOWN = C:\facts\allowsysshutdown_23131_actual.ps1
"allowsysshutdown_23131_actual : $ALLOWSYSSHUTDOWN"
$CASEINSENSNONWINS = C:\facts\caseinsensnonwins_23151_actual.ps1
"caseinsensnonwins_23151_actual : $CASEINSENSNONWINS"
$STRENGTHDEFAULTPERM = C:\facts\strengthdefaultperm_23152_actual.ps1
"strengthdefaultperm_23152_actual : $STRENGTHDEFAULTPERM"
$SETUSRACCCTRL = C:\facts\setusraccctrl_23171_actual.ps1
"setusraccctrl_23171_actual : $SETUSRACCCTRL"
$ELEVATIONPROMPTADMIN = C:\facts\elevationpromptadmin_23172_actual.ps1
"elevationpromptadmin_23172_actual : $ELEVATIONPROMPTADMIN"
$ELEVATIONPROMPTUSR = C:\facts\elevationpromptusr_23173_actual.ps1
"elevationpromptusr_23173_actual : $ELEVATIONPROMPTUSR"
$DETECTAPPINSTAL = C:\facts\detectappinstal_23174_actual.ps1
"detectappinstal_23174_actual : $DETECTAPPINSTAL"
$ELEVATEUIACCESS = C:\facts\elevateuiaccess_23175_actual.ps1
"elevateuiaccess_23175_actual : $ELEVATEUIACCESS"
$RUNALLADMINISTRATOR = C:\facts\runalladministrator_23176_actual.ps1
"runalladministrator_23176_actual : $RUNALLADMINISTRATOR"
$SWITCHSECUREDESKTOP = C:\facts\switchsecuredesktop_23177_actual.ps1
"switchsecuredesktop_23177_actual : $SWITCHSECUREDESKTOP"
$VIRTUALIZEFILEREGISTRY = C:\facts\virtualizefileregistry_23178_actual.ps1
"virtualizefileregistry_23178_actual : $VIRTUALIZEFILEREGISTRY"
$DOMAINFIREWALLSTATE = C:\facts\domainfirewallstate_911_actual.ps1
"domainfirewallstate_911_actual : $DOMAINFIREWALLSTATE"
$INBOUNDCONN = C:\facts\inboundconn_912_actual.ps1
"inboundconn_912_actual : $INBOUNDCONN"
$OUTBOUNDCONN = C:\facts\outboundconn_913_actual.ps1
"outboundconn_913_actual : $OUTBOUNDCONN"
$DISABLENOTIFICDISPLAY = C:\facts\disablenotificdisplay_914_actual.ps1
"disablenotificdisplay_914_actual : $DISABLENOTIFICDISPLAY"
$LOGGINGNAME = C:\facts\loggingname_915_actual.ps1
"loggingname_915_actual : $LOGGINGNAME"
$LOGGINGSIZELIMIT = C:\facts\loggingsizelimit_916_actual.ps1
"loggingsizelimit_916_actual : $LOGGINGSIZELIMIT"
$LOGGINGLOGDROPPACK = C:\facts\logginglogdroppack_917_actual.ps1
"logginglogdroppack_917_actual : $LOGGINGLOGDROPPACK"
$LOGGINGLOGSUCCESS = C:\facts\logginglogsuccess_918_actual.ps1
"logginglogsuccess_918_actual : $LOGGINGLOGSUCCESS"
$PVTFIREWALLSTATE = C:\facts\pvtfirewallstate_921_actual.ps1
"pvtfirewallstate_921_actual : $PVTFIREWALLSTATE"
$PVTINBOUNDCONN = C:\facts\pvtinboundconn_922_actual.ps1
"pvtinboundconn_922_actual : $PVTINBOUNDCONN"
$PVTOUTBOUNDCONN = C:\facts\pvtoutboundconn_923_actual.ps1
"pvtoutboundconn_923_actual : $PVTOUTBOUNDCONN"
$PVTDISABLENOTIFICATION = C:\facts\pvtdisablenotification_924_actual.ps1
"pvtdisablenotification_924_actual : $PVTDISABLENOTIFICATION"
$PVTLOGGINGNAME = C:\facts\pvtloggingname_925_actual.ps1
"pvtloggingname_925_actual : $PVTLOGGINGNAME"
$PVTLOGGINGSIZELIMIT = C:\facts\pvtloggingsizelimit_926_actual.ps1
"pvtloggingsizelimit_926_actual : $PVTLOGGINGSIZELIMIT"
$PVTLOGGINGLOGDROPPACK = C:\facts\pvtlogginglogdroppack_927_actual.ps1
"pvtlogginglogdroppack_927_actual : $PVTLOGGINGLOGDROPPACK"
$PVTLOGGINGLOGSUCCESS = C:\facts\pvtlogginglogsuccess_928_actual.ps1
"pvtlogginglogsuccess_928_actual : $PVTLOGGINGLOGSUCCESS"
$PUBFIREWALLSTATE = C:\facts\pubfirewallstate_931_actual.ps1
"pubfirewallstate_931_actual : $PUBFIREWALLSTATE"
$PUBINBOUNDCONN = C:\facts\pubinboundconn_932_actual.ps1
"pubinboundconn_932_actual : $PUBINBOUNDCONN"
$PUBOUTBOUNDCONN = C:\facts\puboutboundconn_933_actual.ps1
"puboutboundconn_933_actual : $PUBOUTBOUNDCONN"
$PUBDISABLENOTIFICATION = C:\facts\pubdisablenotification_934_actual.ps1
"pubdisablenotification_934_actual : $PUBDISABLENOTIFICATION"
$LOCALFIREWALLRULES = C:\facts\localfirewallrules_935_actual.ps1
"localfirewallrules_935_actual : $LOCALFIREWALLRULES"
$LOCALCONNSECURULES = C:\facts\localconnsecurules_936_actual.ps1
"localconnsecurules_936_actual : $LOCALCONNSECURULES"
$PUBLOGGINGNAME = C:\facts\publoggingname_937_actual.ps1
"publoggingname_937_actual : $PUBLOGGINGNAME"
$PUBLOGGINGSIZELIMIT = C:\facts\publoggingsizelimit_938_actual.ps1
"publoggingsizelimit_938_actual : $PUBLOGGINGSIZELIMIT"
$PUBLOGGINGLOGDROPPACK = C:\facts\publogginglogdroppack_939_actual.ps1
"publogginglogdroppack_939_actual : $PUBLOGGINGLOGDROPPACK"
$PUBLOGGINGLOGSUCCESS = C:\facts\publogginglogsuccess_9310_actual.ps1
"publogginglogsuccess_9310_actual : $PUBLOGGINGLOGSUCCESS"
$AUDCREDVALIDATION = C:\facts\audcredvalidation_1711_actual.ps1
"audcredvalidation_1711_actual : $AUDCREDVALIDATION"
$AUDAPPGRPMANGMENT = C:\facts\audappgrpmangment_1721_actual.ps1
"audappgrpmangment_1721_actual : $AUDAPPGRPMANGMENT"
$AUDSECURGRPMANGMENT = C:\facts\audsecurgrpmangment_1725_actual.ps1
"audsecurgrpmangment_1725_actual : $AUDSECURGRPMANGMENT"
$AUDUSRACCMANGMENT = C:\facts\audusraccmangment_1726_actual.ps1
"audusraccmangment_1726_actual : $AUDUSRACCMANGMENT"
$AUDITPNPACTIVITY = C:\facts\auditpnpactivity_1731_actual.ps1
"auditpnpactivity_1731_actual : $AUDITPNPACTIVITY"
$AUDITPROCESSCREATION = C:\facts\auditprocesscreation_1732_actual.ps1
"auditprocesscreation_1732_actual : $AUDITPROCESSCREATION"
$AUDITACCLOCKOUT = C:\facts\auditacclockout_1751_actual.ps1
"auditacclockout_1751_actual : $AUDITACCLOCKOUT"
$AUDITGRPMEMBERSHIP = C:\facts\auditgrpmembership_1752_actual.ps1
"auditgrpmembership_1752_actual : $AUDITGRPMEMBERSHIP"
$AUDITLOGOFF = C:\facts\auditlogoff_1753_actual.ps1
"auditlogoff_1753_actual : $AUDITLOGOFF"
$AUDITLOGON = C:\facts\auditlogon_1754_actual.ps1
"auditlogon_1754_actual : $AUDITLOGON"
$AUDITOTHERLOGONOFF = C:\facts\auditotherlogonoff_1755_actual.ps1
"auditotherlogonoff_1755_actual : $AUDITOTHERLOGONOFF"
$AUDITSPECIALLOGON = C:\facts\auditspeciallogon_1756_actual.ps1
"auditspeciallogon_1756_actual : $AUDITSPECIALLOGON"
$AUDITDETFILESHARE = C:\facts\auditdetfileshare_1761_actual.ps1
"auditdetfileshare_1761_actual : $AUDITDETFILESHARE"
$AUDITFILESHARE = C:\facts\auditfileshare_1762_actual.ps1
"auditfileshare_1762_actual : $AUDITFILESHARE"
$AUDITOTHEROBJACCESS = C:\facts\auditotherobjaccess_1763_actual.ps1
"auditotherobjaccess_1763_actual : $AUDITOTHEROBJACCESS"
$AUDITREMOVABLESTORAGE = C:\facts\auditremovablestorage_1764_actual.ps1
"auditremovablestorage_1764_actual : $AUDITREMOVABLESTORAGE"
$AUDITPOLICYCHG = C:\facts\auditpolicychg_1771_actual.ps1
"auditpolicychg_1771_actual : $AUDITPOLICYCHG"
$AUDITAUTHENPOLICYCHG = C:\facts\auditauthenpolicychg_1772_actual.ps1
"auditauthenpolicychg_1772_actual : $AUDITAUTHENPOLICYCHG"
$AUDITAUTHORNPOLICYCHG = C:\facts\auditauthornpolicychg_1773_actual.ps1
"auditauthornpolicychg_1773_actual : $AUDITAUTHORNPOLICYCHG"
$AUDITMPRULELEVPOLICYCHG = C:\facts\auditmprulelevpolicychg_1774_actual.ps1
"auditmprulelevpolicychg_1774_actual : $AUDITMPRULELEVPOLICYCHG"
$AUDITOTHERPOLICYCHG = C:\facts\auditotherpolicychg_1775_actual.ps1
"auditotherpolicychg_1775_actual : $AUDITOTHERPOLICYCHG"
$AUDITSENSITIVEPRIVUSE = C:\facts\auditsensitiveprivuse_1781_actual.ps1
"auditsensitiveprivuse_1781_actual : $AUDITSENSITIVEPRIVUSE"
$AUDITIPSECDRIVER = C:\facts\auditipsecdriver_1791_actual.ps1
"auditipsecdriver_1791_actual : $AUDITIPSECDRIVER"
$AUDITOTHERSYSEVENTS = C:\facts\auditothersysevents_1792_actual.ps1
"auditothersysevents_1792_actual : $AUDITOTHERSYSEVENTS"
$AUDITSECURSTATECHG = C:\facts\auditsecurstatechg_1793_actual.ps1
"auditsecurstatechg_1793_actual : $AUDITSECURSTATECHG"
$AUDITSECURSYSEXT = C:\facts\auditsecursysext_1794_actual.ps1
"auditsecursysext_1794_actual : $AUDITSECURSYSEXT"
$AUDITSYSINTEGRITY = C:\facts\auditsysintegrity_1795_actual.ps1
"auditsysintegrity_1795_actual : $AUDITSYSINTEGRITY"
$ENABLELOCKSCREENCAM = C:\facts\enablelockscreencam_18111_actual.ps1
"enablelockscreencam_18111_actual : $ENABLELOCKSCREENCAM"
$ENABLELOCKSCREENSLIDE = C:\facts\enablelockscreenslide_18112_actual.ps1
"enablelockscreenslide_18112_actual : $ENABLELOCKSCREENSLIDE"
$ENABLEONLINESPEECHSERV = C:\facts\enableonlinespeechserv_18122_actual.ps1
"enableonlinespeechserv_18122_actual : $ENABLEONLINESPEECHSERV"
$DISABLEONLINETIPS = C:\facts\disableonlinetips_1813_actual.ps1
"disableonlinetips_1813_actual : $DISABLEONLINETIPS"
$LAPSADMPWD = C:\facts\lapsadmpwd_1821_actual.ps1
"lapsadmpwd_1821_actual : $LAPSADMPWD"
$DONTALLOWPWDEXPIRTIME = C:\facts\dontallowpwdexpirtime_1822_actual.ps1
"dontallowpwdexpirtime_1822_actual : $DONTALLOWPWDEXPIRTIME"
$LOCALADMPWDMANGMENT = C:\facts\localadmpwdmangment_1823_actual.ps1
"localadmpwdmangment_1823_actual : $LOCALADMPWDMANGMENT"
$PWDCOMPLEXITY = C:\facts\pwdcomplexity_1824_actual.ps1
"pwdcomplexity_1824_actual : $PWDCOMPLEXITY"
$PWDLENGTH = C:\facts\pwdlength_1825_actual.ps1
"pwdlength_1825_actual : $PWDLENGTH"
$PWDAGE = C:\facts\pwdage_1826_actual.ps1
"pwdage_1826_actual : $PWDAGE"
$UACRESTRICTLOCALACC = C:\facts\uacrestrictlocalacc_1831_actual.ps1
"uacrestrictlocalacc_1831_actual : $UACRESTRICTLOCALACC"
$CONFSMBCLIENT = C:\facts\confsmbclient_1832_actual.ps1
"confsmbclient_1832_actual : $CONFSMBCLIENT"
$CONFSMBSERVER = C:\facts\confsmbserver_1833_actual.ps1
"confsmbserver_1833_actual : $CONFSMBSERVER"
$ENABLESEHOP = C:\facts\enablesehop_1834_actual.ps1
"enablesehop_1834_actual : $ENABLESEHOP"
$NETBIOSNODETYPE = C:\facts\netbiosnodetype_1836_actual.ps1
"netbiosnodetype_1836_actual : $NETBIOSNODETYPE"
$WDIGESTAUTHEN = C:\facts\wdigestauthen_1837_actual.ps1
"wdigestauthen_1837_actual : $WDIGESTAUTHEN"
$AUTOLOGON = C:\facts\autologon_1841_actual.ps1
"autologon_1841_actual : $AUTOLOGON"
$IPSOURCEROUTING = C:\facts\ipsourcerouting_1842_actual.ps1
"ipsourcerouting_1842_actual : $IPSOURCEROUTING"
$IPSOURCEROUTPROTECT = C:\facts\ipsourceroutprotect_1843_actual.ps1
"ipsourceroutprotect_1843_actual : $IPSOURCEROUTPROTECT"
$ICMPREDIRECTS = C:\facts\icmpredirects_1844_actual.ps1
"icmpredirects_1844_actual : $ICMPREDIRECTS"
$KEEPALIVETIME = C:\facts\keepalivetime_1845_actual.ps1
"keepalivetime_1845_actual : $KEEPALIVETIME"
$NONAMERELEASE = C:\facts\nonamerelease_1846_actual.ps1
"nonamerelease_1846_actual : $NONAMERELEASE"
$PERFROUTDISCOVERY = C:\facts\perfroutdiscovery_1847_actual.ps1
"perfroutdiscovery_1847_actual : $PERFROUTDISCOVERY"
$SAFEDLLSEARCHMODE = C:\facts\safedllsearchmode_1848_actual.ps1
"safedllsearchmode_1848_actual : $SAFEDLLSEARCHMODE"
$SCREENSAVERTIME = C:\facts\screensavertime_1849_actual.ps1
"screensavertime_1849_actual : $SCREENSAVERTIME"
$TCPMAXDATARETRANSIPV6 = C:\facts\tcpmaxdataretransipv6_18410_actual.ps1
"tcpmaxdataretransipv6_18410_actual : $TCPMAXDATARETRANSIPV6"
$TCPMAXDATARETRANS = C:\facts\tcpmaxdataretrans_18411_actual.ps1
"tcpmaxdataretrans_18411_actual : $TCPMAXDATARETRANS"
$WARNINGLEVEL = C:\facts\warninglevel_18412_actual.ps1
"warninglevel_18412_actual : $WARNINGLEVEL"
$TURNOFFMULTICASTNAME = C:\facts\turnoffmulticastname_18541_actual.ps1
"turnoffmulticastname_18541_actual : $TURNOFFMULTICASTNAME"
$FONTPROVIDERS = C:\facts\fontproviders_18551_actual.ps1
"fontproviders_18551_actual : $FONTPROVIDERS"
$INSECUREGUESTLOGON = C:\facts\insecureguestlogon_18581_actual.ps1
"insecureguestlogon_18581_actual : $INSECUREGUESTLOGON"
$MAPPERIODRIVER = C:\facts\mapperiodriver_18591_actual.ps1
"mapperiodriver_18591_actual : $MAPPERIODRIVER"
$RESPONDERDRIVER = C:\facts\responderdriver_18592_actual.ps1
"responderdriver_18592_actual : $RESPONDERDRIVER"
$MSPEERNETSERV = C:\facts\mspeernetserv_185102_actual.ps1
"mspeernetserv_185102_actual : $MSPEERNETSERV"
$CONFNETBRIDGE = C:\facts\confnetbridge_185112_actual.ps1
"confnetbridge_185112_actual : $CONFNETBRIDGE"
$INTERCONNSHARING = C:\facts\interconnsharing_185113_actual.ps1
"interconnsharing_185113_actual : $INTERCONNSHARING"
$DOMAINUSRNETLOC = C:\facts\domainusrnetloc_185114_actual.ps1
"domainusrnetloc_185114_actual : $DOMAINUSRNETLOC"
$HARDENEDUNCPATH = C:\facts\hardeneduncpath_185141_actual.ps1
"hardeneduncpath_185141_actual : $HARDENEDUNCPATH"
$DISABLEIPV6 = C:\facts\disableipv6_1851921_actual.ps1
"disableipv6_1851921_actual : $DISABLEIPV6"
$CONFWIRELESSSET = C:\facts\confwirelessset_185201_actual.ps1
"confwirelessset_185201_actual : $CONFWIRELESSSET"
$WINSCONNECTNOWWIZ = C:\facts\winsconnectnowwiz_185202_actual.ps1
"winsconnectnowwiz_185202_actual : $WINSCONNECTNOWWIZ"
$MINIMIZEINETCONN = C:\facts\minimizeinetconn_185211_actual.ps1
"minimizeinetconn_185211_actual : $MINIMIZEINETCONN"
$PROHCONNNONDOMNET = C:\facts\prohconnnondomnet_185212_actual.ps1
"prohconnnondomnet_185212_actual : $PROHCONNNONDOMNET"
$OFFNOTIFNETUSAGE = C:\facts\offnotifnetusage_18711_actual.ps1
"offnotifnetusage_18711_actual : $OFFNOTIFNETUSAGE"
$CMDLINEPROCESSCREATE = C:\facts\cmdlineprocesscreate_18831_actual.ps1
"cmdlineprocesscreate_18831_actual : $CMDLINEPROCESSCREATE"
$ENCRYPTORACLEREM = C:\facts\encryptoraclerem_18841_actual.ps1
"encryptoraclerem_18841_actual : $ENCRYPTORACLEREM"
$NONEXPORTABLECRED = C:\facts\nonexportablecred_18842_actual.ps1
"nonexportablecred_18842_actual : $NONEXPORTABLECRED"
$TURNONVIRTUAL = C:\facts\turnonvirtual_18851_actual.ps1
"turnonvirtual_18851_actual : $TURNONVIRTUAL"
$TURNONVIRTPLATFORM = C:\facts\turnonvirtplatform_18852_actual.ps1
"turnonvirtplatform_18852_actual : $TURNONVIRTPLATFORM"
$TURNONVIRTCODEINTEG = C:\facts\turnonvirtcodeinteg_18853_actual.ps1
"turnonvirtcodeinteg_18853_actual : $TURNONVIRTCODEINTEG"
$TURNONVIRTUEFIMEM = C:\facts\turnonvirtuefimem_18854_actual.ps1
"turnonvirtuefimem_18854_actual : $TURNONVIRTUEFIMEM"
$TURNONVIRTCREDCONF = C:\facts\turnonvirtcredconf_18855_actual.ps1
"turnonvirtcredconf_18855_actual : $TURNONVIRTCREDCONF"
$ENVBSLAUNCHCONF = C:\facts\envbslaunchconf_18857_actual.ps1
"envbslaunchconf_18857_actual : $ENVBSLAUNCHCONF"
$BOOTSTARTDRIVPOLICY = C:\facts\bootstartdrivpolicy_188141_actual.ps1
"bootstartdrivpolicy_188141_actual : $BOOTSTARTDRIVPOLICY"
$REGPOLBACKGRDPROCESS = C:\facts\regpolbackgrdprocess_188212_actual.ps1
"regpolbackgrdprocess_188212_actual : $REGPOLBACKGRDPROCESS"
$REGPOLGRPPOLICYCHG = C:\facts\regpolgrppolicychg_188213_actual.ps1
"regpolgrppolicychg_188213_actual : $REGPOLGRPPOLICYCHG"
$EXPERDEVICE = C:\facts\experdevice_188214_actual.ps1
"experdevice_188214_actual : $EXPERDEVICE"
$BACKGRPREFRESH = C:\facts\backgrprefresh_188215_actual.ps1
"backgrprefresh_188215_actual : $BACKGRPREFRESH"
$TURNOFFPRINTDRIVER = C:\facts\turnoffprintdriver_1882211_actual.ps1
"turnoffprintdriver_1882211_actual : $TURNOFFPRINTDRIVER"
$TURNOFFDATASHARING = C:\facts\turnoffdatasharing_1882212_actual.ps1
"turnoffdatasharing_1882212_actual : $TURNOFFDATASHARING"
$TURNOFFERRORREPORT = C:\facts\turnofferrorreport_1882213_actual.ps1
"turnofferrorreport_1882213_actual : $TURNOFFERRORREPORT"
$TURNOFFINETCONNWIZ = C:\facts\turnoffinetconnwiz_1882214_actual.ps1
"turnoffinetconnwiz_1882214_actual : $TURNOFFINETCONNWIZ"
$TURNOFFINETDOWNLOAD = C:\facts\turnoffinetdownload_1882215_actual.ps1
"turnoffinetdownload_1882215_actual : $TURNOFFINETDOWNLOAD"
$TURNOFFPRINTING = C:\facts\turnoffprinting_1882216_actual.ps1
"turnoffprinting_1882216_actual : $TURNOFFPRINTING"
$TURNOFFREGISTRY = C:\facts\turnoffregistry_1882217_actual.ps1
"turnoffregistry_1882217_actual : $TURNOFFREGISTRY"
$TURNOFFSEARCHCOMP = C:\facts\turnoffsearchcomp_1882218_actual.ps1
"turnoffsearchcomp_1882218_actual : $TURNOFFSEARCHCOMP"
$TURNOFFORDERPRINTS = C:\facts\turnofforderprints_1882219_actual.ps1
"turnofforderprints_1882219_actual : $TURNOFFORDERPRINTS"
$TURNOFFPUBLISHWEB = C:\facts\turnoffpublishweb_18822110_actual.ps1
"turnoffpublishweb_18822110_actual : $TURNOFFPUBLISHWEB"
$TURNOFFWMCEIP = C:\facts\turnoffwmceip_18822111_actual.ps1
"turnoffwmceip_18822111_actual : $TURNOFFWMCEIP"
$TURNOFFWCEIP = C:\facts\turnoffwceip_18822112_actual.ps1
"turnoffwceip_18822112_actual : $TURNOFFWCEIP"
$TURNOFFWINERROREP = C:\facts\turnoffwinerrorep_18822113_actual.ps1
"turnoffwinerrorep_18822113_actual : $TURNOFFWINERROREP"
$SUPPORTDEVAUTHEN = C:\facts\supportdevauthen_188251_actual.ps1
"supportdevauthen_188251_actual : $SUPPORTDEVAUTHEN"
$ENPOLICYEXTDEVICE = C:\facts\enpolicyextdevice_188261_actual.ps1
"enpolicyextdevice_188261_actual : $ENPOLICYEXTDEVICE"
$DISALLOWCOPYUSRINPUT = C:\facts\disallowcopyusrinput_188271_actual.ps1
"disallowcopyusrinput_188271_actual : $DISALLOWCOPYUSRINPUT"
$BLOCKUSRACC = C:\facts\blockusracc_188281_actual.ps1
"blockusracc_188281_actual : $BLOCKUSRACC"
$DONTDISPLAYNETUI = C:\facts\dontdisplaynetui_188282_actual.ps1
"dontdisplaynetui_188282_actual : $DONTDISPLAYNETUI"
$DONTENUMCONNUSR = C:\facts\dontenumconnusr_188283_actual.ps1
"dontenumconnusr_188283_actual : $DONTENUMCONNUSR"
$ENUMLOCALUSR = C:\facts\enumlocalusr_188284_actual.ps1
"enumlocalusr_188284_actual : $ENUMLOCALUSR"
$TURNOFFAPPNOTFIC = C:\facts\turnoffappnotfic_188285_actual.ps1
"turnoffappnotfic_188285_actual : $TURNOFFAPPNOTFIC"
$TURNOFFPICPWDSIGNIN = C:\facts\turnoffpicpwdsignin_188286_actual.ps1
"turnoffpicpwdsignin_188286_actual : $TURNOFFPICPWDSIGNIN"
$TURNOFFPINSIGNIN = C:\facts\turnoffpinsignin_188287_actual.ps1
"turnoffpinsignin_188287_actual : $TURNOFFPINSIGNIN"
$DISABLECLIPSYNC = C:\facts\disableclipsync_188311_actual.ps1
"disableclipsync_188311_actual : $DISABLECLIPSYNC"
$DISABLEUPLOADUSRACT = C:\facts\disableuploadusract_188312_actual.ps1
"disableuploadusract_188312_actual : $DISABLEUPLOADUSRACT"
$NETCONNONBATTERY = C:\facts\netconnonbattery_1883461_actual.ps1
"netconnonbattery_1883461_actual : $NETCONNONBATTERY"
$NETCONNPLUGGEDIN = C:\facts\netconnpluggedin_1883462_actual.ps1
"netconnpluggedin_1883462_actual : $NETCONNPLUGGEDIN"
$PWDCOMPWAKESONBATTERY = C:\facts\pwdcompwakesonbattery_1883463_actual.ps1
"pwdcompwakesonbattery_1883463_actual : $PWDCOMPWAKESONBATTERY"
$PWDCOMPWAKESPLUGGEDIN = C:\facts\pwdcompwakespluggedin_1883464_actual.ps1
"pwdcompwakespluggedin_1883464_actual : $PWDCOMPWAKESPLUGGEDIN"
$CONFOFFERREMOTEASSIST = C:\facts\confofferremoteassist_188361_actual.ps1
"confofferremoteassist_188361_actual : $CONFOFFERREMOTEASSIST"
$CONFSOLICREMOTEASSIST = C:\facts\confsolicremoteassist_188362_actual.ps1
"confsolicremoteassist_188362_actual : $CONFSOLICREMOTEASSIST"
$RPCEMCLIAUTHEN = C:\facts\rpcemcliauthen_188371_actual.ps1
"rpcemcliauthen_188371_actual : $RPCEMCLIAUTHEN"
$UNAUTHENRPCCLI = C:\facts\unauthenrpccli_188372_actual.ps1
"unauthenrpccli_188372_actual : $UNAUTHENRPCCLI"
$MSDIAGNOSTICTOOL = C:\facts\msdiagnostictool_1884751_actual.ps1
"msdiagnostictool_1884751_actual : $MSDIAGNOSTICTOOL"
$PERFTRACK = C:\facts\perftrack_18847111_actual.ps1
"perftrack_18847111_actual : $PERFTRACK"
$TURNOFFADVERTID = C:\facts\turnoffadvertid_188491_actual.ps1
"turnoffadvertid_188491_actual : $TURNOFFADVERTID"
$ENABLEWINNTPCLI = C:\facts\enablewinntpcli_1885211_actual.ps1
"enablewinntpcli_1885211_actual : $ENABLEWINNTPCLI"
$ENABLEWINNTPSERV = C:\facts\enablewinntpserv_1885212_actual.ps1
"enablewinntpserv_1885212_actual : $ENABLEWINNTPSERV"
$ALLOWWINAPP = C:\facts\allowwinapp_18941_actual.ps1
"allowwinapp_18941_actual : $ALLOWWINAPP"
$ALLOWMSACC = C:\facts\allowmsacc_18961_actual.ps1
"allowmsacc_18961_actual : $ALLOWMSACC"
$AUTOPLAYNONVOLDEV = C:\facts\autoplaynonvoldev_18981_actual.ps1
"autoplaynonvoldev_18981_actual : $AUTOPLAYNONVOLDEV"
$DEFAULTAUTORUN = C:\facts\defaultautorun_18982_actual.ps1
"defaultautorun_18982_actual : $DEFAULTAUTORUN"
$TURNOFFAUTOPLAY = C:\facts\turnoffautoplay_18983_actual.ps1
"turnoffautoplay_18983_actual : $TURNOFFAUTOPLAY"
$CONFANTISPOOF = C:\facts\confantispoof_1891011_actual.ps1
"confantispoof_1891011_actual : $CONFANTISPOOF"
$ALLOWCAMERA = C:\facts\allowcamera_189121_actual.ps1
"allowcamera_189121_actual : $ALLOWCAMERA"
$TURNOFFMSCONSUMER = C:\facts\turnoffmsconsumer_189131_actual.ps1
"turnoffmsconsumer_189131_actual : $TURNOFFMSCONSUMER"
$ENPINPAIRING = C:\facts\enpinpairing_189141_actual.ps1
"enpinpairing_189141_actual : $ENPINPAIRING"
$PWDREVEALBUTTON = C:\facts\pwdrevealbutton_189151_actual.ps1
"pwdrevealbutton_189151_actual : $PWDREVEALBUTTON"
$ADMACCELEVATION = C:\facts\admaccelevation_189152_actual.ps1
"admaccelevation_189152_actual : $ADMACCELEVATION"
$ALLOWTELEMETRY = C:\facts\allowtelemetry_189161_actual.ps1
"allowtelemetry_189161_actual : $ALLOWTELEMETRY"
$CONFAUTHENPROXY = C:\facts\confauthenproxy_189162_actual.ps1
"confauthenproxy_189162_actual : $CONFAUTHENPROXY"
$DONTSHOWFEEDBACKNOTIFIC = C:\facts\dontshowfeedbacknotific_189163_actual.ps1
"dontshowfeedbacknotific_189163_actual : $DONTSHOWFEEDBACKNOTIFIC"
$TOGGLEUSRCONTROL = C:\facts\toggleusrcontrol_189164_actual.ps1
"toggleusrcontrol_189164_actual : $TOGGLEUSRCONTROL"
$APPCONTROLEVENTLOG = C:\facts\appcontroleventlog_1892611_actual.ps1
"appcontroleventlog_1892611_actual : $APPCONTROLEVENTLOG"
$APPMAXLOGFILESIZE = C:\facts\appmaxlogfilesize_1892612_actual.ps1
"appmaxlogfilesize_1892612_actual : $APPMAXLOGFILESIZE"
$SECURCONTROLEVENTLOG = C:\facts\securcontroleventlog_1892621_actual.ps1
"securcontroleventlog_1892621_actual : $SECURCONTROLEVENTLOG"
$SECURMAXLOGFILESIZE = C:\facts\securmaxlogfilesize_1892622_actual.ps1
"securmaxlogfilesize_1892622_actual : $SECURMAXLOGFILESIZE"
$SETUPCONTROLEVENTLOG = C:\facts\setupcontroleventlog_1892631_actual.ps1
"setupcontroleventlog_1892631_actual : $SETUPCONTROLEVENTLOG"
$SETUPMAXLOGFILESIZE = C:\facts\setupmaxlogfilesize_1892632_actual.ps1
"setupmaxlogfilesize_1892632_actual : $SETUPMAXLOGFILESIZE"
$SYSCONTROLEVENTLOG = C:\facts\syscontroleventlog_1892641_actual.ps1
"syscontroleventlog_1892641_actual : $SYSCONTROLEVENTLOG"
$SYSMAXLOGFILESIZE = C:\facts\sysmaxlogfilesize_1892642_actual.ps1
"sysmaxlogfilesize_1892642_actual : $SYSMAXLOGFILESIZE"
$TURNOFFDATAEXEC = C:\facts\turnoffdataexec_189302_actual.ps1
"turnoffdataexec_189302_actual : $TURNOFFDATAEXEC"
$TURNOFFHEAPTERMINATION = C:\facts\turnoffheaptermination_189303_actual.ps1
"turnoffheaptermination_189303_actual : $TURNOFFHEAPTERMINATION"
$TURNOFFSHELLPROTOCOL = C:\facts\turnoffshellprotocol_189304_actual.ps1
"turnoffshellprotocol_189304_actual : $TURNOFFSHELLPROTOCOL"
$TURNOFFLOCATION = C:\facts\turnofflocation_189392_actual.ps1
"turnofflocation_189392_actual : $TURNOFFLOCATION"
$MSGSERVCLOUDSYNC = C:\facts\msgservcloudsync_189431_actual.ps1
"msgservcloudsync_189431_actual : $MSGSERVCLOUDSYNC"
$BLOCKMSACCUSRAUTHEN = C:\facts\blockmsaccusrauthen_189441_actual
"blockmsaccusrauthen_189441_actual : $BLOCKMSACCUSRAUTHEN"
$PREVENTONEDRIVEUSAGE = C:\facts\preventonedriveusage_189521_actual.ps1
"preventonedriveusage_189521_actual : $PREVENTONEDRIVEUSAGE"
$DONTALLOWPWDSAVED = C:\facts\dontallowpwdsaved_1895922_actual.ps1
"dontallowpwdsaved_1895922_actual : $DONTALLOWPWDSAVED"
$RESTRICTREMDESKTOPSERV = C:\facts\restrictremdesktopserv_18959321_actual.ps1
"restrictremdesktopserv_18959321_actual : $RESTRICTREMDESKTOPSERV"
$DONTALLOWCOMPORT = C:\facts\dontallowcomport_18959331_actual.ps1
"dontallowcomport_18959331_actual : $DONTALLOWCOMPORT"
$DONTALLOWDRIVE = C:\facts\dontallowdrive_18959332_actual.ps1
"dontallowdrive_18959332_actual : $DONTALLOWDRIVE"
$DONTALLOWLPTPORT = C:\facts\dontallowlptport_18959333_actual.ps1
"dontallowlptport_18959333_actual : $DONTALLOWLPTPORT"
$DONTALLOWPLUGPLAYDEV = C:\facts\dontallowplugplaydev_18959334_actual.ps1
"dontallowplugplaydev_18959334_actual : $DONTALLOWPLUGPLAYDEV"
$PWDPROMPT = C:\facts\pwdprompt_18959391_actual.ps1
"pwdprompt_18959391_actual : $PWDPROMPT"
$SECURERPCCOMMUNIC = C:\facts\securerpccommunic_18959392_actual.ps1
"securerpccommunic_18959392_actual : $SECURERPCCOMMUNIC"
$ENABLERDPSSL = C:\facts\enablerdpssl_18959393_actual.ps1
"enablerdpssl_18959393_actual : $ENABLERDPSSL"
$ENNETLEVELAUTH = C:\facts\ennetlevelauth_18959394_actual.ps1
"ennetlevelauth_18959394_actual : $ENNETLEVELAUTH"
$SETCLIENTCONN = C:\facts\setclientconn_18959395_actual.ps1
"setclientconn_18959395_actual : $SETCLIENTCONN"
$TIMELIMITACTIVE = C:\facts\timelimitactive_189593101_actual.ps1
"timelimitactive_189593101_actual : $TIMELIMITACTIVE"
$TIMELIMITDISCONSESSION = C:\facts\timelimitdisconsession_189593102_actual.ps1
"timelimitdisconsession_189593102_actual : $TIMELIMITDISCONSESSION"
$DONTDELTEMPFOLDER = C:\facts\dontdeltempfolder_189593111_actual.ps1
"dontdeltempfolder_189593111_actual : $DONTDELTEMPFOLDER"
$DONTUSETEMPFOLDER = C:\facts\dontusetempfolder_189593112_actual.ps1
"dontusetempfolder_189593112_actual : $DONTUSETEMPFOLDER"
$PREVENTDOWNLOAD = C:\facts\preventdownload_189601_actual.ps1
"preventdownload_189601_actual : $PREVENTDOWNLOAD"
$ALLOWCLOUDSEARCH = C:\facts\allowcloudsearch_189612_actual.ps1
"allowcloudsearch_189612_actual : $ALLOWCLOUDSEARCH"
$ALLOWINDEXENCRYPFILE = C:\facts\allowindexencrypfile_189613_actual.ps1
"allowindexencrypfile_189613_actual : $ALLOWINDEXENCRYPFILE"
$TURNOFFKMSCLIONLINE = C:\facts\turnoffkmsclionline_189661_actual.ps1
"turnoffkmsclionline_189661_actual : $TURNOFFKMSCLIONLINE"
$CONFMSMAPS = C:\facts\confmsmaps_1897731_actual.ps1
"confmsmaps_1897731_actual : $CONFMSMAPS"
$JOINMSMAPS = C:\facts\joinmsmaps_1897732_actual.ps1
"joinmsmaps_1897732_actual : $JOINMSMAPS"
$TURNONMONITORING = C:\facts\turnonmonitoring_1897771_actual.ps1
"turnonmonitoring_1897771_actual : $TURNONMONITORING"
$CONFWATSONEVENTS = C:\facts\confwatsonevents_1897791_actual.ps1
"confwatsonevents_1897791_actual : $CONFWATSONEVENTS"
$SCANREMOVABLEDRIVER = C:\facts\scanremovabledriver_18977101_actual.ps1
"scanremovabledriver_18977101_actual : $SCANREMOVABLEDRIVER"
$TURNONEMAILSCAN = C:\facts\turnonemailscan_18977102_actual.ps1
"turnonemailscan_18977102_actual : $TURNONEMAILSCAN"
$CONFASRRULE = C:\facts\confasrrule_189771311_actual.ps1
"confasrrule_189771311_actual : $CONFASRRULE"
$SETASRRULE = C:\facts\setasrrule_189771312_actual.ps1
"setasrrule_189771312_actual : $SETASRRULE"
$PREVENTUSRAPPS = C:\facts\preventusrapps_189771331_actual.ps1
"preventusrapps_189771331_actual : $PREVENTUSRAPPS"
$CONFDETECTUNWANAPP = C:\facts\confdetectunwanapp_1897714_actual.ps1
"confdetectunwanapp_1897714_actual : $CONFDETECTUNWANAPP"
$TURNOFFWINDEFENDERANTIVIRUS = C:\facts\turnoffwindefenderantivirus_1897715_actual.ps1
"turnoffwindefenderantivirus_1897715_actual : $TURNOFFWINDEFENDERANTIVIRUS"
$CONFWINDEFENDSMARTSCREEN = C:\facts\confwindefendsmartscreen_1898011_actual.ps1
"confwindefendsmartscreen_1898011_actual : $CONFWINDEFENDSMARTSCREEN"
$ALLOWSUGGESTAPPS = C:\facts\allowsuggestapps_189841_actual.ps1
"allowsuggestapps_189841_actual : $ALLOWSUGGESTAPPS"
$ALLOWWININKWORKSPACE = C:\facts\allowwininkworkspace_189842_actual.ps1
"allowwininkworkspace_189842_actual : $ALLOWWININKWORKSPACE"
$ALLOWUSRCONTROL = C:\facts\allowusrcontrol_189851_actual.ps1
"allowusrcontrol_189851_actual : $ALLOWUSRCONTROL"
$ELEVATEDPRIVIL = C:\facts\elevatedprivil_189852_actual.ps1
"elevatedprivil_189852_actual : $ELEVATEDPRIVIL"
$PREVIESECURPROMPT = C:\facts\previesecurprompt_189853_actual.ps1
"previesecurprompt_189853_actual : $PREVIESECURPROMPT"
$SIGNINLASTINTERACTIVEUSR = C:\facts\signinlastinteractiveusr_189861_actual.ps1
"signinlastinteractiveusr_189861_actual : $SIGNINLASTINTERACTIVEUSR"
$PSHELLSCRIPTBLOCKLOG = C:\facts\pshellscriptblocklog_189951_actual.ps1
"pshellscriptblocklog_189951_actual : $PSHELLSCRIPTBLOCKLOG"
$PSHELLTRANSCRIPTION = C:\facts\pshelltranscription_189952_actual.ps1
"pshelltranscription_189952_actual : $PSHELLTRANSCRIPTION"
$ALLOWBASICAUTHEN = C:\facts\allowbasicauthen_1899711_actual.ps1
"allowbasicauthen_1899711_actual : $ALLOWBASICAUTHEN"
$ALLOWUNENCRYPTRAFFIC = C:\facts\allowunencryptraffic_1899712_actual.ps1
"allowunencryptraffic_1899712_actual : $ALLOWUNENCRYPTRAFFIC"
$DISALLOWDIGESTAUTHEN = C:\facts\disallowdigestauthen_1899713_actual.ps1
"disallowdigestauthen_1899713_actual : $DISALLOWDIGESTAUTHEN"
$WINRMALLOWBASICAUTHEN = C:\facts\winrmallowbasicauthen_1899721_actual.ps1
"winrmallowbasicauthen_1899721_actual : $WINRMALLOWBASICAUTHEN"
$ALLOWREMOTESERVMANAGMENT = C:\facts\allowremoteservmanagment_1899722_actual.ps1
"allowremoteservmanagment_1899722_actual : $ALLOWREMOTESERVMANAGMENT"
$WINRMALLOWENCRYPTRAFFIC = C:\facts\winrmallowencryptraffic_1899723_actual.ps1
"winrmallowencryptraffic_1899723_actual : $WINRMALLOWENCRYPTRAFFIC"
$DISALLOWWINRM = C:\facts\disallowwinrm_1899724_actual.ps1
"disallowwinrm_1899724_actual : $DISALLOWWINRM"
$ALLOWREMOTESHELLACCESS = C:\facts\allowremoteshellaccess_189981_actual.ps1
"allowremoteshellaccess_189981_actual : $ALLOWREMOTESHELLACCESS"
$PREVUSRMODIFYSETTING = C:\facts\prevusrmodifysetting_1899921_actual.ps1
"prevusrmodifysetting_1899921_actual : $PREVUSRMODIFYSETTING"
$MANAGEPREVIEWBUILDS = C:\facts\managepreviewbuilds_18910211_actual.ps1
"managepreviewbuilds_18910211_actual : $MANAGEPREVIEWBUILDS"
$PREVIEWBUILDSFEATURE = C:\facts\previewbuildsfeature_18910212_actual.ps1
"previewbuildsfeature_18910212_actual : $PREVIEWBUILDSFEATURE"
$QUALITYUPDATES = C:\facts\qualityupdates_18910213_actual.ps1
"qualityupdates_18910213_actual : $QUALITYUPDATES"
$CONFAUTOUPDATES = C:\facts\confautoupdates_1891022_actual.ps1
"confautoupdates_1891022_actual : $CONFAUTOUPDATES"
$CONFAUTOUPDATESDAY = C:\facts\confautoupdatesday_1891023_actual.ps1
"confautoupdatesday_1891023_actual : $CONFAUTOUPDATESDAY"
$NOAUTORESTART = C:\facts\noautorestart_1891024_actual.ps1
"noautorestart_1891024_actual : $NOAUTORESTART"
$ENABLESCRNSAV = C:\facts\enablescrnsav_19131_actual.ps1
"enablescrnsav_19131_actual : $ENABLESCRNSAV"
$FORSPECSCRNSAV = C:\facts\forspecscrnsav_19132_actual.ps1
"forspecscrnsav_19132_actual : $FORSPECSCRNSAV"
$PASSPROSCRNSAV = C:\facts\passproscrnsav_19133_actual.ps1
"passproscrnsav_19133_actual : $PASSPROSCRNSAV"
$SCRNSAVTIMEOUT = C:\facts\scrnsavtimeout_19134_actual.ps1
"scrnsavtimeout_19134_actual : $SCRNSAVTIMEOUT"
$TOASTNOTIFLOCKSCRN = C:\facts\toastnotiflockscrn_19511_actual.ps1
"toastnotiflockscrn_19511_actual : $TOASTNOTIFLOCKSCRN"
$HELPEXPIMPROGRM = C:\facts\helpexpimprogram_196611_actual.ps1
"helpexpimprogram_196611_actual : $HELPEXPIMPROGRM"
$PREZONEINFILE = C:\facts\prezoneinfile_19741_actual.ps1
"prezoneinfile_19741_actual : $PREZONEINFILE"
$NOTIFYANTIPROGRAMPEN = C:\facts\notifyantiprogramopen_19742_actual.ps1
"notifyantiprogramopen_19742_actual : $NOTIFYANTIPROGRAMPEN"
$CONFWINSPOTLOCKSCRN = C:\facts\confwinspotlockscrn_19771_actual.ps1
"confwinspotlockscrn_19771_actual : $CONFWINSPOTLOCKSCRN"
$THIRDPARTYWINSPOT = C:\facts\thirdpartywinspot_19772_actual.ps1
"thirdpartywinspot_19772_actual : $THIRDPARTYWINSPOT"
$DIADATATAILEXP = C:\facts\diagdatatailexp_19773_actual.ps1
"diagdatatailexp_19773_actual : $DIADATATAILEXP"
$WINSPOTFEATURE = C:\facts\winspotfeature_19774_actual.ps1
"winspotfeature_19774_actual : $WINSPOTFEATURE"
$PREVUSERSHARPROF = C:\facts\prevusersharprof_197261_actual.ps1
"prevusersharprof_197261_actual : $PREVUSERSHARPROF"
$INSTALLELEVPRIVILEG = C:\facts\installelevprivileg_197411_actual.ps1
"installelevprivileg_197411_actual : $INSTALLELEVPRIVILEG"
$PREVCODECDOWN = C:\facts\prevcodecdown_1974521_actual.ps1
"prevcodecdown_1974521_actual : $PREVCODECDOWN"