$ENFPWDHIST = C:\facts\enfpwdhist_111_audit.ps1
"enfpwdhist_111_audit : $ENFPWDHIST"
$MAXPWDAGE = C:\facts\maxpwdage_112_audit.ps1
"maxpwdage_112_audit : $MAXPWDAGE"
$MINPWDAGE = C:\facts\minpwdage_113_audit.ps1
"minpwdage_113_audit : $MINPWDAGE"
$MINPWDLEN = C:\facts\minpwdlen_114_audit.ps1
"minpwdlen_114_audit : $MINPWDLEN"
$PWDCOMPLEX = C:\facts\pwdcomplex_115_audit.ps1
"pwdcomplex_115_audit : $PWDCOMPLEX"
$REVERSEPATH = C:\facts\reversepath_116_audit.ps1
"reversepath_116_audit : $REVERSEPATH"
$ACCLOCKDUR = C:\facts\acclockdur_121_audit.ps1
"acclockdur_121_audit : $ACCLOCKDUR"
$ACCLOCKTHRES = C:\facts\acclockthres_122_audit.ps1
"acclockthres_122_audit : $ACCLOCKTHRES"
$RESETACCLOCK = C:\facts\resetacclock_123_audit.ps1
"resetacclock_123_audit : $RESETACCLOCK"
$ACCESSCREDMGR = C:\facts\accesscredmgr_221_audit.ps1
"accesscredmgr_221_audit : $ACCESSCREDMGR"
$ACCESSCOMPDC = C:\facts\accesscompdc_222_audit.ps1
"accesscompdc_222_audit : $ACCESSCOMPDC"
$ACTASPARTOPER = C:\facts\actaspartoper_224_audit.ps1
"actaspartoper_224_audit : $ACTASPARTOPER"
$ADDWSDOMAIN = C:\facts\addwsdomain_225_audit.ps1
"addwsdomain_225_audit : $ADDWSDOMAIN"
$MEMQUOTAPROCESS = C:\facts\memquotaprocess_226_audit.ps1
"memquotaprocess_226_audit : $MEMQUOTAPROCESS"
$ALLOWLOGLOCAL = C:\facts\allowloglocal_227_audit.ps1
"allowloglocal_227_audit : $ALLOWLOGLOCAL"
$ALLOWLOGREMDESKDC = C:\facts\allowlogremdeskdc_228_audit.ps1
"allowlogremdeskdc_228_audit : $ALLOWLOGREMDESKDC"
$BACKUPFILEDIRS = C:\facts\backupfiledirs_2210_audit.ps1
"backupfiledirs_2210_audit : $BACKUPFILEDIRS"
$CHGSYSTIME = C:\facts\chgsystime_2211_audit.ps1
"chgsystime_2211_audit : $CHGSYSTIME"
$CHGTIMEZONE = C:\facts\chgtimezone_2212_audit.ps1
"chgtimezone_2212_audit : $CHGTIMEZONE"
$PAGEFILE = C:\facts\pagefile_2213_audit.ps1
"pagefile_2213_audit : $PAGEFILE"
$TOKENOBJ = C:\facts\tokenobj_2214_audit.ps1
"tokenobj_2214_audit : $TOKENOBJ"
$GLOBALOBJ = C:\facts\globalobj_2215_audit.ps1
"globalobj_2215_audit : $GLOBALOBJ"
$PERMSHAREDOBJ = C:\facts\permsharedobj_2216_audit.ps1
"permsharedobj_2216_audit : $PERMSHAREDOBJ"
$SYMBOLICLINKSDC = C:\facts\symboliclinksdc_2217_audit.ps1
"symboliclinksdc_2217_audit : $SYMBOLICLINKSDC"
$DEBUGPROG = C:\facts\debugprog_2219_audit.ps1
"debugprog_2219_audit : $DEBUGPROG"
$DENYACCESSDC = C:\facts\denyaccessdc_2220_audit.ps1
"denyaccessdc_2220_audit : $DENYACCESSDC"
$DENYLOGBATCHJOB = C:\facts\denylogbatchjob_2222_audit.ps1
"denylogbatchjob_2222_audit : $DENYLOGBATCHJOB"
$DENYLOGSERVICE = C:\facts\denylogservice_2223_audit.ps1
"denylogservice_2223_audit : $DENYLOGSERVICE"
$DENYLOGLOCALLY = C:\facts\denyloglocally_2224_audit.ps1
"denyloglocally_2224_audit : $DENYLOGLOCALLY"
$DENYLOGREMDESKDC = C:\facts\denylogremdeskdc_2225_audit.ps1
"denylogremdeskdc_2225_audit : $DENYLOGREMDESKDC"
$ENBCOMPUSRACCDC = C:\facts\enbcompusraccdc_2227_audit.ps1
"enbcompusraccdc_2227_audit : $ENBCOMPUSRACCDC"
$FORCESHUTDOWN = C:\facts\forceshutdown_2229_audit.ps1
"forceshutdown_2229_audit : $FORCESHUTDOWN"
$SECURITYAUDITS = C:\facts\securityaudits_2230_audit.ps1
"securityaudits_2230_audit : $SECURITYAUDITS"
$CLIENTAUTHENDC = C:\facts\clientauthendc_2231_audit.ps1
"clientauthendc_2231_audit : $CLIENTAUTHENDC"
$INCSCHEDPRIOR = C:\facts\incschedprior_2233_audit.ps1
"incschedprior_2233_audit : $INCSCHEDPRIOR"
$LOADUNLOADDEVDRIVER = C:\facts\loadunloaddevdriver_2234_audit.ps1
"loadunloaddevdriver_2234_audit : $LOADUNLOADDEVDRIVER"
$LOCKPAGEMEM = C:\facts\lockpagemem_2235_audit.ps1
"lockpagemem_2235_audit : $LOCKPAGEMEM"
$LOGBATCHJOB = C:\facts\logbatchjob_2236_audit.ps1
"logbatchjob_2236_audit : $LOGBATCHJOB"
$AUDSECURLOGDC = C:\facts\audsecurlogdc_2237_audit.ps1
"audsecurlogdc_2237_audit : $AUDSECURLOGDC"
$MODOBJLABEL = C:\facts\modobjlabel_2239_audit.ps1
"modobjlabel_2239_audit : $MODOBJLABEL"
$MODFIRMENV = C:\facts\modfirmenv_2240_audit.ps1
"modfirmenv_2240_audit : $MODFIRMENV"
$VOLMAINTASKS = C:\facts\volmaintasks_2241_audit.ps1
"volmaintasks_2241_audit : $VOLMAINTASKS"
$PROFSINGLEPO = C:\facts\profsinglepro_2242_audit.ps1
"profsinglepro_2242_audit : $PROFSINGLEPO"
$PROFSYSPERF = C:\facts\profsysperf_2243_audit.ps1
"profsysperf_2243_audit : $PROFSYSPERF"
$REPLPROTAKEN = C:\facts\replprotoken_2244_audit.ps1
"replprotoken_2244_audit : $REPLPROTAKEN"
$RESTOREFILEDIRS = C:\facts\restorefiledirs_2245_audit.ps1
"restorefiledirs_2245_audit : $RESTOREFILEDIRS"
$SHUTDOWNSYS = C:\facts\shutdownsys_2246_audit.ps1
"shutdownsys_2246_audit : $SHUTDOWNSYS"
$SYNCDIRSERDATA = C:\facts\syncdirserdata_2247_audit.ps1
"syncdirserdata_2247_audit : $SYNCDIRSERDATA"
$OWNERSHIPFILE = C:\facts\ownershipfile_2248_audit.ps1
"ownershipfile_2248_audit : $OWNERSHIPFILE"
$LIMITLOCACCUSE = C:\facts\limitlocaccuse_2313_audit.ps1
"limitlocaccuse_2313_audit : $LIMITLOCACCUSE"
$RENAMEADMACC = C:\facts\renameadmacc_2314_audit.ps1
"renameadmacc_2314_audit : $RENAMEADMACC"
$RENAMEGUESTACC = C:\facts\renameguestacc_2315_audit.ps1
"renameguestacc_2315_audit : $RENAMEGUESTACC"
$FORCEAUDPOLICY = C:\facts\forceaudpolicy_2321_audit.ps1
"forceaudpolicy_2321_audit : $FORCEAUDPOLICY"
$SYSSHUTDOWNSECURAUD = C:\facts\sysshutdownsecuraud_2322_audit.ps1
"sysshutdownsecuraud_2322_audit : $SYSSHUTDOWNSECURAUD"
$ALLOWREMOVMEDIA = C:\facts\allowremovmedia_2341_audit.ps1
"allowremovmedia_2341_audit : $ALLOWREMOVMEDIA"
$PREVENTUSR = C:\facts\preventusr_2342_audit.ps1
"preventusr_2342_audit : $PREVENTUSR"
$ALLOWSERVSCHEDTASK = C:\facts\allowservschedtask_2351_audit.ps1
"allowservschedtask_2351_audit : $ALLOWSERVSCHEDTASK"
$LDAPSERVSIGN = C:\facts\ldapservsign_2352_audit.ps1
"ldapservsign_2352_audit : $LDAPSERVSIGN"
$REFUSEMACHACCPWD = C:\facts\refusemachaccpwd_2353_audit.ps1
"refusemachaccpwd_2353_audit : $REFUSEMACHACCPWD"
$DIGIENCRYPTSIGN = C:\facts\digiencryptsign_2361_audit.ps1
"digiencryptsign_2361_audit : $DIGIENCRYPTSIGN"
$DIGIENCRYPSECDATA = C:\facts\digiencrypsecdata_2362_audit.ps1
"digiencrypsecdata_2362_audit : $DIGIENCRYPSECDATA"
$DIGISIGNSECDATA = C:\facts\digisignsecdata_2363_audit.ps1
"digisignsecdata_2363_audit : $DIGISIGNSECDATA"
$DISMACHACCPWDCHG = C:\facts\dismachaccpwdchg_2364_audit.ps1
"dismachaccpwdchg_2364_audit : $DISMACHACCPWDCHG"
$MAXMACHACCPWDAGE = C:\facts\maxmachaccpwdage_2365_audit.ps1
"maxmachaccpwdage_2365_audit : $MAXMACHACCPWDAGE"
$REQSESSIONKEY = C:\facts\reqsessionkey_2366_audit.ps1
"reqsessionkey_2366_audit : $REQSESSIONKEY"
$DONTDISPLASTUSRNAME = C:\facts\dontdisplastusrname_2371_audit.ps1
"dontdisplastusrname_2371_audit : $DONTDISPLASTUSRNAME"
$DONTREQCTRLALTDEL = C:\facts\dontreqctrlaltdel_2372_audit.ps1
"dontreqctrlaltdel_2372_audit : $DONTREQCTRLALTDEL"
$MSGTEXTUSR = C:\facts\msgtextusr_2373_audit.ps1
"msgtextusr_2373_audit : $MSGTEXTUSR"
$MSGTITLEUSR = C:\facts\msgtitleusr_2374_audit.ps1
"msgtitleusr_2374_audit : $MSGTITLEUSR"
$PROMPTUSRCHGPWD = C:\facts\promptusrchgpwd_2376_audit.ps1
"promptusrchgpwd_2376_audit : $PROMPTUSRCHGPWD"
$SMARTCARDREMOVAL = C:\facts\smartcardremoval_2378_audit.ps1
"smartcardremoval_2378_audit : $SMARTCARDREMOVAL"
$DIGISIGNCLIENT = C:\facts\digisignclient_2381_audit.ps1
"digisignclient_2381_audit : $DIGISIGNCLIENT"
$DIGISIGNSERVAGREE = C:\facts\digisignservagree_2382_audit.ps1
"digisignservagree_2382_audit : $DIGISIGNSERVAGREE"
$SENDUNENCRYPPWD = C:\facts\sendunencryppwd_2383_audit.ps1
"sendunencryppwd_2383_audit : $SENDUNENCRYPPWD"
$SETIDLETIME = C:\facts\setidletime_2391_audit.ps1
"setidletime_2391_audit : $SETIDLETIME"
$DIGISIGNSERV = C:\facts\digisignserv_2392_audit.ps1
"digisignserv_2392_audit : $DIGISIGNSERV"
$DIGISIGNCLIAGREE = C:\facts\digisigncliagree_2393_audit.ps1
"digisigncliagree_2393_audit : $DIGISIGNCLIAGREE"
$DISCONCLILOGONHREXP = C:\facts\disconclilogonhrexp_2394_audit.ps1
"disconclilogonhrexp_2394_audit : $DISCONCLILOGONHREXP"
$ALLOWANONYSID = C:\facts\allowanonysid_23101_audit.ps1
"allowanonysid_23101_audit : $ALLOWANONYSID"
$DONTALLOWSTORAGEPWDCRED = C:\facts\dontallowstoragepwdcred_23104_audit.ps1
"dontallowstoragepwdcred_23104_audit : $DONTALLOWSTORAGEPWDCRED"
$ANONYUSRPERM = C:\facts\anonyusrperm_23105_audit.ps1
"anonyusrperm_23105_audit : $ANONYUSRPERM"
$NAMEDPIPESDC = C:\facts\namedpipesdc_23106_audit.ps1
"namedpipesdc_23106_audit : $NAMEDPIPESDC"
$REMOTEACCESREGPATH = C:\facts\remoteaccesregpath_23108_audit.ps1
"remoteaccesregpath_23108_audit : $REMOTEACCESREGPATH"
$REMOTEACCESREGSUBPATH = C:\facts\remoteaccesregsubpath_23109_audit.ps1
"remoteaccesregsubpath_23109_audit : $REMOTEACCESREGSUBPATH"
$RESTRICTANONYACCES = C:\facts\restrictanonyacces_231010_audit.ps1
"restrictanonyacces_231010_audit : $RESTRICTANONYACCES"
$SHARESACCESS = C:\facts\sharesaccess_231011_audit.ps1
"sharesaccess_231011_audit : $SHARESACCESS"
$SHARESECURLOCALACC = C:\facts\sharesecurlocalacc_231012_audit.ps1
"sharesecurlocalacc_231012_audit : $SHARESECURLOCALACC"
$ALLOWLOCALSYS = C:\facts\allowlocalsys_23111_audit.ps1
"allowlocalsys_23111_audit : $ALLOWLOCALSYS"
$ALLOWLOCALSYSNULL = C:\facts\allowlocalsysnull_23112_audit.ps1
"allowlocalsysnull_23112_audit : $ALLOWLOCALSYSNULL"
$ALLOWPKU2UAUTHEN = C:\facts\allowpku2uauthen_23113_audit.ps1
"allowpku2uauthen_23113_audit : $ALLOWPKU2UAUTHEN"
$KERBEROSENCRYP = C:\facts\kerberosencryp_23114_audit.ps1
"kerberosencryp_23114_audit : $KERBEROSENCRYP"
$DONTSTORELANHASHVAL = C:\facts\dontstorelanhashval_23115_audit.ps1
"dontstorelanhashval_23115_audit : $DONTSTORELANHASHVAL"
$FORCELOGOFF = C:\facts\forcelogoff_23116_audit.ps1
"forcelogoff_23116_audit : $FORCELOGOFF"
$LANMGRAUTHEN = C:\facts\lanmgrauthen_23117_audit.ps1
"lanmgrauthen_23117_audit : $LANMGRAUTHEN"
$LDAPCLISIGN = C:\facts\ldapclisign_23118_audit.ps1
"ldapclisign_23118_audit : $LDAPCLISIGN"
$MINSESSIONSECURCLI = C:\facts\minsessionsecurcli_23119_audit.ps1
"minsessionsecurcli_23119_audit : $MINSESSIONSECURCLI"
$MINSESSIONSECURSERV = C:\facts\minsessionsecurserv_231110_audit.ps1
"minsessionsecurserv_231110_audit : $MINSESSIONSECURSERV"
$ALLOWSYSSHUTDOWN = C:\facts\allowsysshutdown_23131_audit.ps1
"allowsysshutdown_23131_audit : $ALLOWSYSSHUTDOWN"
$CASEINSENSNONWINS = C:\facts\caseinsensnonwins_23151_audit.ps1
"caseinsensnonwins_23151_audit : $CASEINSENSNONWINS"
$STRENGTHDEFAULTPERM = C:\facts\strengthdefaultperm_23152_audit.ps1
"strengthdefaultperm_23152_audit : $STRENGTHDEFAULTPERM"
$SYSSETOPTNSUBSYSTEMS = C:\facts\syssetoptnsubsystems_23161_audit.ps1
"syssetoptnsubsystems_23161_audit : $SYSSETOPTNSUBSYSTEMS"
$SETUSRACCCTRL = C:\facts\setusraccctrl_23171_audit.ps1
"setusraccctrl_23171_audit : $SETUSRACCCTRL"
$ELEVATIONPROMPTADMIN = C:\facts\elevationpromptadmin_23172_audit.ps1
"elevationpromptadmin_23172_audit : $ELEVATIONPROMPTADMIN"
$ELEVATIONPROMPTUSR = C:\facts\elevationpromptusr_23173_audit.ps1
"elevationpromptusr_23173_audit : $ELEVATIONPROMPTUSR"
$DETECTAPPINSTAL = C:\facts\detectappinstal_23174_audit.ps1
"detectappinstal_23174_audit : $DETECTAPPINSTAL"
$ELEVATEUIACCESS = C:\facts\elevateuiaccess_23175_audit.ps1
"elevateuiaccess_23175_audit : $ELEVATEUIACCESS"
$RUNALLADMINISTRATOR = C:\facts\runalladministrator_23176_audit.ps1
"runalladministrator_23176_audit : $RUNALLADMINISTRATOR"
$SWITCHSECUREDESKTOP = C:\facts\switchsecuredesktop_23177_audit.ps1
"switchsecuredesktop_23177_audit : $SWITCHSECUREDESKTOP"
$VIRTUALIZEFILEREGISTRY = C:\facts\virtualizefileregistry_23178_audit.ps1
"virtualizefileregistry_23178_audit : $VIRTUALIZEFILEREGISTRY"
$DOMAINFIREWALLSTATE = C:\facts\domainfirewallstate_911_audit.ps1
"domainfirewallstate_911_audit : $DOMAINFIREWALLSTATE"
$INBOUNDCONN = C:\facts\inboundconn_912_audit.ps1
"inboundconn_912_audit : $INBOUNDCONN"
$OUTBOUNDCONN = C:\facts\outboundconn_913_audit.ps1
"outboundconn_913_audit : $OUTBOUNDCONN"
$DISABLENOTIFICDISPLAY = C:\facts\disablenotificdisplay_914_audit.ps1
"disablenotificdisplay_914_audit : $DISABLENOTIFICDISPLAY"
$LOGGINGNAME = C:\facts\loggingname_915_audit.ps1
"loggingname_915_audit : $LOGGINGNAME"
$LOGGINGSIZELIMIT = C:\facts\loggingsizelimit_916_audit.ps1
"loggingsizelimit_916_audit : $LOGGINGSIZELIMIT"
$LOGGINGLOGDROPPACK = C:\facts\logginglogdroppack_917_audit.ps1
"logginglogdroppack_917_audit : $LOGGINGLOGDROPPACK"
$LOGGINGLOGSUCCESS = C:\facts\logginglogsuccess_918_audit.ps1
"logginglogsuccess_918_audit : $LOGGINGLOGSUCCESS"
$PVTFIREWALLSTATE = C:\facts\pvtfirewallstate_921_audit.ps1
"pvtfirewallstate_921_audit : $PVTFIREWALLSTATE"
$PVTINBOUNDCONN = C:\facts\pvtinboundconn_922_audit.ps1
"pvtinboundconn_922_audit : $PVTINBOUNDCONN"
$PVTOUTBOUNDCONN = C:\facts\pvtoutboundconn_923_audit.ps1
"pvtoutboundconn_923_audit : $PVTOUTBOUNDCONN"
$PVTDISABLENOTIFICATION = C:\facts\pvtdisablenotification_924_audit.ps1
"pvtdisablenotification_924_audit : $PVTDISABLENOTIFICATION"
$PVTLOGGINGNAME = C:\facts\pvtloggingname_925_audit.ps1
"pvtloggingname_925_audit : $PVTLOGGINGNAME"
$PVTLOGGINGSIZELIMIT = C:\facts\pvtloggingsizelimit_926_audit.ps1
"pvtloggingsizelimit_926_audit : $PVTLOGGINGSIZELIMIT"
$PVTLOGGINGLOGDROPPACK = C:\facts\pvtlogginglogdroppack_927_audit.ps1
"pvtlogginglogdroppack_927_audit : $PVTLOGGINGLOGDROPPACK"
$PVTLOGGINGLOGSUCCESS = C:\facts\pvtlogginglogsuccess_928_audit.ps1
"pvtlogginglogsuccess_928_audit : $PVTLOGGINGLOGSUCCESS"
$PUBFIREWALLSTATE = C:\facts\pubfirewallstate_931_audit.ps1
"pubfirewallstate_931_audit : $PUBFIREWALLSTATE"
$PUBINBOUNDCONN = C:\facts\pubinboundconn_932_audit.ps1
"pubinboundconn_932_audit : $PUBINBOUNDCONN"
$PUBOUTBOUNDCONN = C:\facts\puboutboundconn_933_audit.ps1
"puboutboundconn_933_audit : $PUBOUTBOUNDCONN"
$PUBDISABLENOTIFICATION = C:\facts\pubdisablenotification_934_audit.ps1
"pubdisablenotification_934_audit : $PUBDISABLENOTIFICATION"
$LOCALFIREWALLRULES = C:\facts\localfirewallrules_935_audit.ps1
"localfirewallrules_935_audit : $LOCALFIREWALLRULES"
$LOCALCONNSECURULES = C:\facts\localconnsecurules_936_audit.ps1
"localconnsecurules_936_audit : $LOCALCONNSECURULES"
$PUBLOGGINGNAME = C:\facts\publoggingname_937_audit.ps1
"publoggingname_937_audit : $PUBLOGGINGNAME"
$PUBLOGGINGSIZELIMIT = C:\facts\publoggingsizelimit_938_audit.ps1
"publoggingsizelimit_938_audit : $PUBLOGGINGSIZELIMIT"
$PUBLOGGINGLOGDROPPACK = C:\facts\publogginglogdroppack_939_audit.ps1
"publogginglogdroppack_939_audit : $PUBLOGGINGLOGDROPPACK"
$PUBLOGGINGLOGSUCCESS = C:\facts\publogginglogsuccess_9310_audit.ps1
"publogginglogsuccess_9310_audit : $PUBLOGGINGLOGSUCCESS"
$AUDCREDVALIDATION = C:\facts\audcredvalidation_1711_audit.ps1
"audcredvalidation_1711_audit : $AUDCREDVALIDATION"
$AUDKERBEROSAUTHEN = C:\facts\audkerberosauthen_1712_audit.ps1
"audkerberosauthen_1712_audit : $AUDKERBEROSAUTHEN"
$AUDKERBEROSSRVTICK = C:\facts\audkerberossrvtick_1713_audit.ps1
"audkerberossrvtick_1713_audit : $AUDKERBEROSSRVTICK"
$AUDAPPGRPMANGMENT = C:\facts\audappgrpmangment_1721_audit.ps1
"audappgrpmangment_1721_audit : $AUDAPPGRPMANGMENT"
$AUDCOMPACCMANGMENT = C:\facts\audcompaccmangment_1722_audit.ps1
"audcompaccmangment_1722_audit : $AUDCOMPACCMANGMENT"
$AUDDISTRIBGRPMANGMENT = C:\facts\auddistribgrpmangment_1723_audit.ps1
"auddistribgrpmangment_1723_audit : $AUDDISTRIBGRPMANGMENT"
$AUDOTHERACCMANGMENT = C:\facts\audotheraccmangment_1724_audit.ps1
"audotheraccmangment_1724_audit : $AUDOTHERACCMANGMENT"
$AUDSECURGRPMANGMENT = C:\facts\audsecurgrpmangment_1725_audit.ps1
"audsecurgrpmangment_1725_audit : $AUDSECURGRPMANGMENT"
$AUDUSRACCMANGMENT = C:\facts\audusraccmangment_1726_audit.ps1
"audusraccmangment_1726_audit : $AUDUSRACCMANGMENT"
$AUDITPROCESSCREATION = C:\facts\auditprocesscreation_1731_audit.ps1
"auditprocesscreation_1731_audit : $AUDITPROCESSCREATION"
$AUDITDIRSERVACCESS = C:\facts\auditdirservaccess_1741_audit.ps1
"auditdirservaccess_1741_audit : $AUDITDIRSERVACCESS"
$AUDITDIRSERVCHG = C:\facts\auditdirservchg_1742_audit.ps1
"auditdirservchg_1742_audit : $AUDITDIRSERVCHG"
$AUDITACCLOCKOUT = C:\facts\auditacclockout_1751_audit.ps1
"auditacclockout_1751_audit : $AUDITACCLOCKOUT"
$AUDITLOGOFF = C:\facts\auditlogoff_1752_audit.ps1
"auditlogoff_1752_audit : $AUDITLOGOFF"
$AUDITLOGON = C:\facts\auditlogon_1753_audit.ps1
"auditlogon_1753_audit : $AUDITLOGON"
$AUDITOTHERLOGONOFF = C:\facts\auditotherlogonoff_1754_audit.ps1
"auditotherlogonoff_1754_audit : $AUDITOTHERLOGONOFF"
$AUDITSPECIALLOGON = C:\facts\auditspeciallogon_1755_audit.ps1
"auditspeciallogon_1755_audit : $AUDITSPECIALLOGON"
$AUDDTAILEDFILESHRE = C:\facts\auddtailedfileshre_1761_audit.ps1
"auddtailedfileshre_1761_audit : $AUDDTAILEDFILESHRE"
$AUDFILESHARE = C:\facts\audfileshare_1762_audit.ps1
"audfileshare_1762_audit : $AUDFILESHARE"
$AUDITOTHEROBJACCESS = C:\facts\auditotherobjaccess_1763_audit.ps1
"auditotherobjaccess_1763_audit : $AUDITOTHEROBJACCESS"
$AUDITPOLICYCHG = C:\facts\auditpolicychg_1771_audit.ps1
"auditpolicychg_1771_audit : $AUDITPOLICYCHG"
$AUDITAUTHENPOLICYCHG = C:\facts\auditauthenpolicychg_1772_audit.ps1
"auditauthenpolicychg_1772_audit : $AUDITAUTHENPOLICYCHG"
$AUDITAUTHORNPOLICYCHG = C:\facts\auditauthornpolicychg_1773_audit.ps1
"auditauthornpolicychg_1773_audit : $AUDITAUTHORNPOLICYCHG"
$AUDMPSSVCRULELEVELPOLICYCHG = C:\facts\audmpssvcrulelevelpolicychg_1774_audit.ps1
"audmpssvcrulelevelpolicychg_1774_audit : $AUDMPSSVCRULELEVELPOLICYCHG"
$AUDOTHRPOLICYCHG = C:\facts\audothrpolicychg_1775_audit.ps1
"audothrpolicychg_1775_audit : $AUDOTHRPOLICYCHG"
$AUDITSENSITIVEPRIVUSE = C:\facts\auditsensitiveprivuse_1781_audit.ps1
"auditsensitiveprivuse_1781_audit : $AUDITSENSITIVEPRIVUSE"
$AUDITIPSECDRIVER = C:\facts\auditipsecdriver_1791_audit.ps1
"auditipsecdriver_1791_audit : $AUDITIPSECDRIVER"
$AUDITOTHERSYSEVENTS = C:\facts\auditothersysevents_1792_audit.ps1
"auditothersysevents_1792_audit : $AUDITOTHERSYSEVENTS"
$AUDITSECURSTATECHG = C:\facts\auditsecurstatechg_1793_audit.ps1
"auditsecurstatechg_1793_audit : $AUDITSECURSTATECHG"
$AUDITSECURSYSEXT = C:\facts\auditsecursysext_1794_audit.ps1
"auditsecursysext_1794_audit : $AUDITSECURSYSEXT"
$AUDITSYSINTEGRITY = C:\facts\auditsysintegrity_1795_audit.ps1
"auditsysintegrity_1795_audit : $AUDITSYSINTEGRITY"
$CONFSMBENABLE = C:\facts\confsmbenable_1832_audit.ps1
"confsmbenable_1832_audit : $CONFSMBENABLE"
$CONFSMBCLIENT = C:\facts\confsmbclient_1833_audit.ps1
"confsmbclient_1833_audit : $CONFSMBCLIENT"
$CONFSMBSERVER = C:\facts\confsmbserver_1834_audit.ps1
"confsmbserver_1834_audit : $CONFSMBSERVER"
$ENABLESEHOP = C:\facts\enablesehop_1835_audit.ps1
"enablesehop_1835_audit : $ENABLESEHOP"
$ENABLEEXPROTLDAP = C:\facts\enableexprotldap_1836_audit.ps1
"enableexprotldap_1836_audit : $ENABLEEXPROTLDAP"
$NETBIOSNODETYPE = C:\facts\netbiosnodetype_1837_audit.ps1
"netbiosnodetype_1837_audit : $NETBIOSNODETYPE"
$WDIGESTAUTHEN = C:\facts\wdigestauthen_1838_audit.ps1
"wdigestauthen_1838_audit : $WDIGESTAUTHEN"
$AUTOLOGON = C:\facts\autologon_1841_audit.ps1
"autologon_1841_audit : $AUTOLOGON"
$IPSOURCEROUTING = C:\facts\ipsourcerouting_1842_audit.ps1
"ipsourcerouting_1842_audit : $IPSOURCEROUTING"
$IPSOURCEROUTPROTECT = C:\facts\ipsourceroutprotect_1843_audit.ps1
"ipsourceroutprotect_1843_audit : $IPSOURCEROUTPROTECT"
$ICMPREDIRECTS = C:\facts\icmpredirects_1844_audit.ps1
"icmpredirects_1844_audit : $ICMPREDIRECTS"
$KEEPALIVETIME = C:\facts\keepalivetime_1845_audit.ps1
"keepalivetime_1845_audit : $KEEPALIVETIME"
$NONAMERELEASE = C:\facts\nonamerelease_1846_audit.ps1
"nonamerelease_1846_audit : $NONAMERELEASE"
$PERFROUTDISCOVERY = C:\facts\perfroutdiscovery_1847_audit.ps1
"perfroutdiscovery_1847_audit : $PERFROUTDISCOVERY"
$SAFEDLLSEARCHMODE = C:\facts\safedllsearchmode_1848_audit.ps1
"safedllsearchmode_1848_audit : $SAFEDLLSEARCHMODE"
$SCREENSAVERTIME = C:\facts\screensavertime_1849_audit.ps1
"screensavertime_1849_audit : $SCREENSAVERTIME"
$TCPMAXDATARETRANSIPV6 = C:\facts\tcpmaxdataretransipv6_18410_audit.ps1
"tcpmaxdataretransipv6_18410_audit : $TCPMAXDATARETRANSIPV6"
$TCPMAXDATARETRANS = C:\facts\tcpmaxdataretrans_18411_audit.ps1
"tcpmaxdataretrans_18411_audit : $TCPMAXDATARETRANS"
$WARNINGLEVEL = C:\facts\warninglevel_18412_audit.ps1
"warninglevel_18412_audit : $WARNINGLEVEL"
$TURNOFFMULTICASTNAME = C:\facts\turnoffmulticastname_18541_audit.ps1
"turnoffmulticastname_18541_audit : $TURNOFFMULTICASTNAME"
$MAPPERIODRIVER = C:\facts\mapperiodriver_18591_audit.ps1
"mapperiodriver_18591_audit : $MAPPERIODRIVER"
$RESPONDERDRIVER = C:\facts\responderdriver_18592_audit.ps1
"responderdriver_18592_audit : $RESPONDERDRIVER"
$MSPEERNETSERV = C:\facts\mspeernetserv_185102_audit.ps1
"mspeernetserv_185102_audit : $MSPEERNETSERV"
$CONFNETBRIDGE = C:\facts\confnetbridge_185112_audit.ps1
"confnetbridge_185112_audit : $CONFNETBRIDGE"
$DOMAINUSRNETLOC = C:\facts\domainusrnetloc_185113_audit.ps1
"domainusrnetloc_185113_audit : $DOMAINUSRNETLOC"
$HARDENEDUNCPATH = C:\facts\hardeneduncpath_185141_audit.ps1
"hardeneduncpath_185141_audit : $HARDENEDUNCPATH"
$DISABLEIPV6 = C:\facts\disableipv6_1851921_audit.ps1
"disableipv6_1851921_audit : $DISABLEIPV6"
$CONFWIRELESSSET = C:\facts\confwirelessset_185201_audit.ps1
"confwirelessset_185201_audit : $CONFWIRELESSSET"
$WINSCONNECTNOWWIZ = C:\facts\winsconnectnowwiz_185202_audit.ps1
"winsconnectnowwiz_185202_audit : $WINSCONNECTNOWWIZ"
$CMDLINEPROCESSCREATE = C:\facts\cmdlineprocesscreate_18831_audit.ps1
"cmdlineprocesscreate_18831_audit : $CMDLINEPROCESSCREATE"
$ENCRYPTORACLEREM = C:\facts\encryptoraclerem_18841_audit.ps1
"encryptoraclerem_18841_audit : $ENCRYPTORACLEREM"
$ALLOWREMOTERPC = C:\facts\allowremoterpc_18872_audit.ps1
"allowremoterpc_18872_audit : $ALLOWREMOTERPC"
$REGPOLBACKGRDPROCESS = C:\facts\regpolbackgrdprocess_188212_audit.ps1
"regpolbackgrdprocess_188212_audit : $REGPOLBACKGRDPROCESS"
$REGPOLGRPPOLICYCHG = C:\facts\regpolgrppolicychg_188213_audit.ps1
"regpolgrppolicychg_188213_audit : $REGPOLGRPPOLICYCHG"
$BACKGRPREFRESH = C:\facts\backgrprefresh_188214_audit.ps1
"backgrprefresh_188214_audit : $BACKGRPREFRESH"
$TURNOFFPRINTDRIVER = C:\facts\turnoffprintdriver_1882211_audit.ps1
"turnoffprintdriver_1882211_audit : $TURNOFFPRINTDRIVER"
$TURNOFFDATASHARING = C:\facts\turnoffdatasharing_1882212_audit.ps1
"turnoffdatasharing_1882212_audit : $TURNOFFDATASHARING"
$TURNOFFERRORREPORT = C:\facts\turnofferrorreport_1882213_audit.ps1
"turnofferrorreport_1882213_audit : $TURNOFFERRORREPORT"
$TURNOFFINETCONNWIZ = C:\facts\turnoffinetconnwiz_1882214_audit.ps1
"turnoffinetconnwiz_1882214_audit : $TURNOFFINETCONNWIZ"
$TURNOFFINETDOWNLOAD = C:\facts\turnoffinetdownload_1882215_audit.ps1
"turnoffinetdownload_1882215_audit : $TURNOFFINETDOWNLOAD"
$TURNOFFINETFILE = C:\facts\turnoffinetfile_1882216_audit.ps1
"turnoffinetfile_1882216_audit : $TURNOFFINETFILE"
$TURNOFFPRINTING = C:\facts\turnoffprinting_1882217_audit.ps1
"turnoffprinting_1882217_audit : $TURNOFFPRINTING"
$TURNOFFREGISTRY = C:\facts\turnoffregistry_1882218_audit.ps1
"turnoffregistry_1882218_audit : $TURNOFFREGISTRY"
$TURNOFFSEARCHCOMP = C:\facts\turnoffsearchcomp_1882219_audit.ps1
"turnoffsearchcomp_1882219_audit : $TURNOFFSEARCHCOMP"
$TURNOFFORDERPRINTS = C:\facts\turnofforderprints_18822110_audit.ps1
"turnofforderprints_18822110_audit : $TURNOFFORDERPRINTS"
$TURNOFFPUBLISHWEB = C:\facts\turnoffpublishweb_18822111_audit.ps1
"turnoffpublishweb_18822111_audit : $TURNOFFPUBLISHWEB"
$TURNOFFWMCEIP = C:\facts\turnoffwmceip_18822112_audit.ps1
"turnoffwmceip_18822112_audit : $TURNOFFWMCEIP"
$TURNOFFWCEIP = C:\facts\turnoffwceip_18822113_audit.ps1
"turnoffwceip_18822113_audit : $TURNOFFWCEIP"
$TURNOFFWINERROREP = C:\facts\turnoffwinerrorep_18822114_audit.ps1
"turnoffwinerrorep_18822114_audit : $TURNOFFWINERROREP"
$PWDCOMPWAKESONBATTERY = C:\facts\pwdcompwakesonbattery_1883461_audit.ps1
"pwdcompwakesonbattery_1883461_audit : $PWDCOMPWAKESONBATTERY"
$PWDCOMPWAKESPLUGGEDIN = C:\facts\pwdcompwakespluggedin_1883462_audit.ps1
"pwdcompwakespluggedin_1883462_audit : $PWDCOMPWAKESPLUGGEDIN"
$CONFOFFERREMOTEASSIST = C:\facts\confofferremoteassist_188361_audit.ps1
"confofferremoteassist_188361_audit : $CONFOFFERREMOTEASSIST"
$CONFSOLICREMOTEASSIST = C:\facts\confsolicremoteassist_188362_audit.ps1
"confsolicremoteassist_188362_audit : $CONFSOLICREMOTEASSIST"
$MSDIAGNOSTICTOOL = C:\facts\msdiagnostictool_1884751_audit.ps1
"msdiagnostictool_1884751_audit : $MSDIAGNOSTICTOOL"
$PERFTRACK = C:\facts\perftrack_18847111_audit.ps1
"perftrack_18847111_audit : $PERFTRACK"
$ENABLEWINNTPCLI = C:\facts\enablewinntpcli_1885211_audit.ps1
"enablewinntpcli_1885211_audit : $ENABLEWINNTPCLI"
$AUTOPLAYNONVOLDEV = C:\facts\autoplaynonvoldev_18981_audit.ps1
"autoplaynonvoldev_18981_audit : $AUTOPLAYNONVOLDEV"
$DEFAULTAUTORUN = C:\facts\defaultautorun_18982_audit.ps1
"defaultautorun_18982_audit : $DEFAULTAUTORUN"
$TURNOFFAUTOPLAY = C:\facts\turnoffautoplay_18983_audit.ps1
"turnoffautoplay_18983_audit : $TURNOFFAUTOPLAY"
$PWDREVEALBUTTON = C:\facts\pwdrevealbutton_189151_audit.ps1
"pwdrevealbutton_189151_audit : $PWDREVEALBUTTON"
$ADMACCELEVATION = C:\facts\admaccelevation_189152_audit.ps1
"admaccelevation_189152_audit : $ADMACCELEVATION"
$TURNOFFDESKTOP = C:\facts\turnoffdesktop_189181_audit.ps1
"turnoffdesktop_189181_audit : $TURNOFFDESKTOP"
$TURNOFFUSERDESKTOP = C:\facts\turnoffuserdesktop_189182_audit.ps1
"turnoffuserdesktop_189182_audit : $TURNOFFUSERDESKTOP"
$EMET = C:\facts\emet_189241_audit.ps1
"emet_189241_audit : $EMET"
$ENMITIGATIONSETTING = C:\facts\enmitigationsetting_189242_audit.ps1
"enmitigationsetting_189242_audit : $ENMITIGATIONSETTING"
$ENDEFAULTIE = C:\facts\endefaultie_189243_audit.ps1
"endefaultie_189243_audit : $ENDEFAULTIE"
$ENDEFPOPSOFTWARE = C:\facts\endefpopsoftware_189244_audit.ps1
"endefpopsoftware_189244_audit : $ENDEFPOPSOFTWARE"
$ENDEFRECSOFWARE = C:\facts\endefrecsofware_189245_audit.ps1
"endefrecsofware_189245_audit : $ENDEFRECSOFWARE"
$ENAPPOPTINASLR = C:\facts\enappoptinaslr_189246_audit.ps1
"enappoptinaslr_189246_audit : $ENAPPOPTINASLR"
$ENAPPOPTOUTDEP = C:\facts\enappoptoutdep_189247_audit.ps1
"enappoptoutdep_189247_audit : $ENAPPOPTOUTDEP"
$ENAPPOPTOUTSEHOP = C:\facts\enappoptoutsehop_189248_audit.ps1
"enappoptoutsehop_189248_audit : $ENAPPOPTOUTSEHOP"
$APPCONTROLEVENTLOG = C:\facts\appcontroleventlog_1892611_audit.ps1
"appcontroleventlog_1892611_audit : $APPCONTROLEVENTLOG"
$APPMAXLOGFILESIZE = C:\facts\appmaxlogfilesize_1892612_audit.ps1
"appmaxlogfilesize_1892612_audit : $APPMAXLOGFILESIZE"
$SECURCONTROLEVENTLOG = C:\facts\securcontroleventlog_1892621_audit.ps1
"securcontroleventlog_1892621_audit : $SECURCONTROLEVENTLOG"
$SECURMAXLOGFILESIZE = C:\facts\securmaxlogfilesize_1892622_audit.ps1
"securmaxlogfilesize_1892622_audit : $SECURMAXLOGFILESIZE"
$SETUPCONTROLEVENTLOG = C:\facts\setupcontroleventlog_1892631_audit.ps1
"setupcontroleventlog_1892631_audit : $SETUPCONTROLEVENTLOG"
$SETUPMAXLOGFILESIZE = C:\facts\setupmaxlogfilesize_1892632_audit.ps1
"setupmaxlogfilesize_1892632_audit : $SETUPMAXLOGFILESIZE"
$SYSCONTROLEVENTLOG = C:\facts\syscontroleventlog_1892641_audit.ps1
"syscontroleventlog_1892641_audit : $SYSCONTROLEVENTLOG"
$SYSMAXLOGFILESIZE = C:\facts\sysmaxlogfilesize_1892642_audit.ps1
"sysmaxlogfilesize_1892642_audit : $SYSMAXLOGFILESIZE"
$TURNOFFDATAEXEC = C:\facts\turnoffdataexec_189302_audit.ps1
"turnoffdataexec_189302_audit : $TURNOFFDATAEXEC"
$TURNOFFHEAPTERMINATION = C:\facts\turnoffheaptermination_189303_audit.ps1
"turnoffheaptermination_189303_audit : $TURNOFFHEAPTERMINATION"
$TURNOFFSHELLPROTOCOL = C:\facts\turnoffshellprotocol_189304_audit.ps1
"turnoffshellprotocol_189304_audit : $TURNOFFSHELLPROTOCOL"
$TURNOFFLOCATION = C:\facts\turnofflocation_189392_audit.ps1
"turnofflocation_189392_audit : $TURNOFFLOCATION"
$PREVENTONEDRIVEUSAGE = C:\facts\preventonedriveusage_189521_audit.ps1
"preventonedriveusage_189521_audit : $PREVENTONEDRIVEUSAGE"
$PREVENTONEDRIVEWIN81 = C:\facts\preventonedrivewin81_189522_audit.ps1
"preventonedrivewin81_189522_audit : $PREVENTONEDRIVEWIN81"
$DONTALLOWPWDSAVED = C:\facts\dontallowpwdsaved_1895922_audit.ps1
"dontallowpwdsaved_1895922_audit : $DONTALLOWPWDSAVED"
$RESTRICTREMDESKTOPSERV = C:\facts\restrictremdesktopserv_18959321_audit.ps1
"restrictremdesktopserv_18959321_audit : $RESTRICTREMDESKTOPSERV"
$DONTALLOWCOMPORT = C:\facts\dontallowcomport_18959331_audit.ps1
"dontallowcomport_18959331_audit : $DONTALLOWCOMPORT"
$DONTALLOWDRIVE = C:\facts\dontallowdrive_18959332_audit.ps1
"dontallowdrive_18959332_audit : $DONTALLOWDRIVE"
$DONTALLOWLPTPORT = C:\facts\dontallowlptport_18959333_audit.ps1
"dontallowlptport_18959333_audit : $DONTALLOWLPTPORT"
$DONTALLOWPLUGPLAYDEV = C:\facts\dontallowplugplaydev_18959334_audit.ps1
"dontallowplugplaydev_18959334_audit : $DONTALLOWPLUGPLAYDEV"
$PWDPROMPT = C:\facts\pwdprompt_18959391_audit.ps1
"pwdprompt_18959391_audit : $PWDPROMPT"
$SECURERPCCOMMUNIC = C:\facts\securerpccommunic_18959392_audit.ps1
"securerpccommunic_18959392_audit : $SECURERPCCOMMUNIC"
$ENABLERDPSSL = C:\facts\enablerdpssl_18959393_audit.ps1
"enablerdpssl_18959393_audit : $ENABLERDPSSL"
$ENNETLEVELAUTH = C:\facts\ennetlevelauth_18959394_audit.ps1
"ennetlevelauth_18959394_audit : $ENNETLEVELAUTH"
$SETCLIENTCONN = C:\facts\setclientconn_18959395_audit.ps1
"setclientconn_18959395_audit : $SETCLIENTCONN"
$TIMELIMITACTIVE = C:\facts\timelimitactive_189593101_audit.ps1
"timelimitactive_189593101_audit : $TIMELIMITACTIVE"
$TIMELIMITDISCONSESSION = C:\facts\timelimitdisconsession_189593102_audit.ps1
"timelimitdisconsession_189593102_audit : $TIMELIMITDISCONSESSION"
$DONTDELTEMPFOLDER = C:\facts\dontdeltempfolder_189593111_audit.ps1
"dontdeltempfolder_189593111_audit : $DONTDELTEMPFOLDER"
$DONTUSETEMPFOLDER = C:\facts\dontusetempfolder_189593112_audit.ps1
"dontusetempfolder_189593112_audit : $DONTUSETEMPFOLDER"
$PREVENTDOWNLOAD = C:\facts\preventdownload_189601_audit.ps1
"preventdownload_189601_audit : $PREVENTDOWNLOAD"
$ALLOWINDEXENCRYPFILE = C:\facts\allowindexencrypfile_189612_audit.ps1
"allowindexencrypfile_189612_audit : $ALLOWINDEXENCRYPFILE"
$JOINMSMAPS = C:\facts\joinmsmaps_1897731_audit.ps1
"joinmsmaps_1897731_audit : $JOINMSMAPS"
$TURNOFFWINDEFENDERANTIVIRUS = C:\facts\turnoffwindefenderantivirus_1897714_audit.ps1
"turnoffwindefenderantivirus_1897714_audit : $TURNOFFWINDEFENDERANTIVIRUS"
$CONFDEFAULTCONSENT = C:\facts\confdefaultconsent_1898121_audit.ps1
"confdefaultconsent_1898121_audit : $CONFDEFAULTCONSENT"
$ALLOWUSRCONTROL = C:\facts\allowusrcontrol_189851_audit.ps1
"allowusrcontrol_189851_audit : $ALLOWUSRCONTROL"
$ELEVATEDPRIVIL = C:\facts\elevatedprivil_189852_audit.ps1
"elevatedprivil_189852_audit : $ELEVATEDPRIVIL"
$PREVIESECURPROMPT = C:\facts\previesecurprompt_189853_audit.ps1
"previesecurprompt_189853_audit : $PREVIESECURPROMPT"
$PSHELLSCRIPTBLOCKLOG = C:\facts\pshellscriptblocklog_189951_audit.ps1
"pshellscriptblocklog_189951_audit : $PSHELLSCRIPTBLOCKLOG"
$PSHELLTRANSCRIPTION = C:\facts\pshelltranscription_189952_audit.ps1
"pshelltranscription_189952_audit : $PSHELLTRANSCRIPTION"
$ALLOWBASICAUTHEN = C:\facts\allowbasicauthen_1899711_audit.ps1
"allowbasicauthen_1899711_audit : $ALLOWBASICAUTHEN"
$ALLOWUNENCRYPTRAFFIC = C:\facts\allowunencryptraffic_1899712_audit.ps1
"allowunencryptraffic_1899712_audit : $ALLOWUNENCRYPTRAFFIC"
$DISALLOWDIGESTAUTHEN = C:\facts\disallowdigestauthen_1899713_audit.ps1
"disallowdigestauthen_1899713_audit : $DISALLOWDIGESTAUTHEN"
$WINRMALLOWBASICAUTHEN = C:\facts\winrmallowbasicauthen_1899721_audit.ps1
"winrmallowbasicauthen_1899721_audit : $WINRMALLOWBASICAUTHEN"
$ALLOWREMOTESERVMANAGMENT = C:\facts\allowremoteservmanagment_1899722_audit.ps1
"allowremoteservmanagment_1899722_audit : $ALLOWREMOTESERVMANAGMENT"
$WINRMALLOWENCRYPTRAFFIC = C:\facts\winrmallowencryptraffic_1899723_audit.ps1
"winrmallowencryptraffic_1899723_audit : $WINRMALLOWENCRYPTRAFFIC"
$DISALLOWWINRM = C:\facts\disallowwinrm_1899724_audit.ps1
"disallowwinrm_1899724_audit : $DISALLOWWINRM"
$ALLOWREMOTESHELLACCESS = C:\facts\allowremoteshellaccess_189981_audit.ps1
"allowremoteshellaccess_189981_audit : $ALLOWREMOTESHELLACCESS"
$CONFAUTOUPDATES = C:\facts\confautoupdates_1891022_audit.ps1
"confautoupdates_1891022_audit : $CONFAUTOUPDATES"
$CONFAUTOUPDATESDAY = C:\facts\confautoupdatesday_1891023_audit.ps1
"confautoupdatesday_1891023_audit : $CONFAUTOUPDATESDAY"
$INSTALLUPGRSHUTDIS = C:\facts\installupgrshutdis_1891024_audit.ps1
"installupgrshutdis_1891024_audit : $INSTALLUPGRSHUTDIS"
$UPGRESHUTWINDIAL = C:\facts\upgreshutwindial_1891025_audit.ps1
"upgreshutwindial_1891025_audit : $UPGRESHUTWINDIAL"
$NOAUTORESTART = C:\facts\noautorestart_1891026_audit.ps1
"noautorestart_1891026_audit.ps1 $NOAUTORESTART"
$RESCHAUTOUPDATE = C:\facts\reschautoupdate_1891027_audit.ps1
"reschautoupdate_1891027_audit : $RESCHAUTOUPDATE"
$ENABLESCRNSAV = C:\facts\enablescrnsav_19131_audit.ps1
"enablescrnsav_19131_audit : $ENABLESCRNSAV"
$FORSPECSCRNSAV = C:\facts\forspecscrnsav_19132_audit.ps1
"forspecscrnsav_19132_audit : $FORSPECSCRNSAV"
$PASSPROSCRNSAV = C:\facts\passproscrnsav_19133_audit.ps1
"passproscrnsav_19133_audit : $PASSPROSCRNSAV"
$SCRNSAVTIMEOUT = C:\facts\scrnsavtimeout_19134_audit.ps1
"scrnsavtimeout_19134_audit : $SCRNSAVTIMEOUT"
$HELPEXPIMPROGRM = C:\facts\helpexpimprogram_196611_audit.ps1
"helpexpimprogram_196611_audit : $HELPEXPIMPROGRM"
$PREZONEINFILE = C:\facts\prezoneinfile_19741_audit.ps1
"prezoneinfile_19741_audit : $PREZONEINFILE"
$NOTIFYANTIPROGRAMPEN = C:\facts\notifyantiprogramopen_19742_audit.ps1
"notifyantiprogramopen_19742_audit : $NOTIFYANTIPROGRAMPEN"
$PREVUSERSHARPROF = C:\facts\prevusersharprof_197261_audit.ps1
"prevusersharprof_197261_audit : $PREVUSERSHARPROF"
$INSTALLELEVPRIVILEG = C:\facts\installelevprivileg_197411_audit.ps1
"installelevprivileg_197411_audit : $INSTALLELEVPRIVILEG"
$PREVCODECDOWN = C:\facts\prevcodecdown_1974521_audit.ps1
"prevcodecdown_1974521_audit : $PREVCODECDOWN"
